website/docs/r/project_hook.html.markdown
=> Fix gotcha in doc: tag -> notes

gitlab/resource_gitlab_project.go
Deleting a project in Gitlab is an async method.
By blocking until the project does not exist anymore, we
do not lie to the terraform end user about the status of a
deleted project.
As a side effet it fixes the acceptances tests.
=> gitlab_project: wait until real deletion

gitlab/provider.go
This will help our users to figure out that we moved to the v4 api.
=> Fail when using api v3

gitlab/resource_gitlab_group.go, gitlab/resource_gitlab_group_test.go
=> gitlab_group: enable imports

gitlab/provider.go, gitlab/resource_gitlab_user.go, gitlab/resource_gitlab_user_test.go, website/docs/r/user.html.markdown, website/gitlab.erb
Rebase of #11 against v4 API
```
$ make testacc 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-gitlab        [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (2.22s)
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (0.70s)
=== RUN   TestAccGitlabLabel_basic
--- PASS: TestAccGitlabLabel_basic (2.38s)
=== RUN   TestAccGitlabProjectHook_basic
--- PASS: TestAccGitlabProjectHook_basic (2.06s)
=== RUN   TestAccGitlabProject_basic
--- PASS: TestAccGitlabProject_basic (2.09s) …
```
=> new resource: gitlab_user

gitlab/resource_gitlab_project.go, gitlab/resource_gitlab_project_test.go
=> Enable gitlab_project import

CHANGELOG.md
=> Add changelog for #28

gitlab/resource_gitlab_deploy_key.go, gitlab/resource_gitlab_deploy_key_test.go
=> Make deploy keys indempotent when newlines are added

gitlab/config.go
=> Respect http proxy environment variables.

gitlab/resource_gitlab_project.go, gitlab/util.go
https://github.com/xanzy/go-gitlab/blob/cd1e3f03a766cd7f9a7d2257926039b77f2c7710/gitlab.go#L66-L77
=> Use new access levels permissions

.travis.yml, gitlab/resource_gitlab_group.go, scripts/start-gitlab.sh
=> Run ACC tests

website/docs/r/project_cluster.html.markdown, website/gitlab.erb
Documentation for `gitlab_project_cluster` implemented in #87.
=> Docs for gitlab_project_cluster

gitlab/provider.go, gitlab/resource_gitlab_tag_protection.go, gitlab/resource_gitlab_tag_protection_test.go, website/docs/r/branch_protection.html.markdown, website/docs/r/tag_protection.html.markdown
=> Add tag protection

gitlab/resource_gitlab_pipeline_trigger.go
=> Resolve triggers pagination issue by calling GetPipelineTrigger

gitlab/resource_gitlab_label.go
This PR is based on a review for group_labels resource PR -> https://github.com/terraform-providers/terraform-provider-gitlab/pull/186
=> Return an error if project label is not found

website/docs/r/group_membership.html.markdown
Change `access_level` available value `master` to `maintainer`.
Using Gitlab 12.4.2.
=> Update `access_level` available values

gitlab/data_source_gitlab_group.go, gitlab/resource_gitlab_group.go, website/docs/d/group.html.markdown, website/docs/r/group.html.markdown
=> Add group runners token to the group data source/resource

gitlab/data_source_gitlab_project.go, gitlab/resource_gitlab_project.go, gitlab/resource_gitlab_project_test.go, website/docs/d/project.html.markdown, website/docs/r/project.html.markdown
=> Implement pipelines_enabled parameter for gitlab_project

gitlab/resource_gitlab_label.go, gitlab/resource_gitlab_label_test.go
=> Read labels on all pages

go.mod, go.sum, vendor/github.com/xanzy/go-gitlab/event_types.go, vendor/github.com/xanzy/go-gitlab/projects.go, vendor/github.com/xanzy/go-gitlab/users.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/oauth2/README.md, vendor/modules.txt
=> Update go-gitlab to v0.22.3

gitlab/resource_gitlab_project.go, gitlab/resource_gitlab_project_test.go
This PR is work-in-progress and a request for comments.
Depends on: #245 
`go-gitlab` library supports project transferral between namespaces since version 0.22.3. With this support, it is possible to support this from the provider by checking the `namespace_id` property. If it is changed from the old value, the intent is to transfer the project.
Will add tests later, but comments on the production code is welcome.
=> When changing the namespace_id, transfer project from old to new namespace

gitlab/resource_gitlab_group_variable.go, gitlab/resource_gitlab_group_variable_test.go, website/docs/r/group_variable.html.markdown
Related issue https://github.com/terraform-providers/terraform-provider-gitlab/issues/243
=> Add masked attribute to group variables

gitlab/data_source_gitlab_project.go, gitlab/resource_gitlab_project.go, website/docs/d/project.html.markdown, website/docs/r/project.html.markdown
=> add attribute remove_source_branch_after_merge to projects

gitlab/resource_gitlab_group.go, gitlab/resource_gitlab_group_test.go
=> Handle async groups API deletion ack response in tests

README.md, gitlab/helper_test.go, gitlab/resource_gitlab_project_push_rules_test.go
=> Move isRunningInCE and isRunningInEE in their own helper

gitlab/resource_gitlab_user.go, gitlab/resource_gitlab_user_test.go
Rebased #288, no other change.
closes #193, closes #288
=> Improvements to resource_gitlab_user import

gitlab/data_source_gitlab_group_membership.go, gitlab/data_source_gitlab_group_membership_test.go, gitlab/provider.go, website/docs/d/group_membership.html.markdown, website/gitlab.erb
=> Add new data source gitlab_group_membership

gitlab/resource_gitlab_project.go, gitlab/resource_gitlab_project_test.go, website/docs/r/project.html.markdown
Supersedes #142 and #164 
Closes #42 
Closes #164 
Thank you Joep and Daniel for the initial work on this feature!
Third time's the charm? I started from #164 and added commits to address the reviewer feedback.
=> Add import_url to gitlab_project

gitlab/resource_gitlab_project_variable.go, gitlab/resource_gitlab_project_variable_test.go
Closes #371 
Rather than adding validation I intercepted the error.
Old error:
```
Error: POST https://gitlab.com/api/v4/projects/12345678/variables: 400 {message: {value: [is invalid]}}
```
New error:
```
Error: Invalid value for a masked variable. Check the masked variable requirements: https://docs.gitlab.com/ee/ci/variables/#masked-variable-requirements
```
=> gitlab_project_variable: friendlier error when masked variable is invalid

gitlab/provider.go, gitlab/resource_gitlab_service_github.go, gitlab/resource_gitlab_service_pipelines_email.go, gitlab/resource_gitlab_service_pipelines_email_test.go, gitlab/resource_gitlab_service_slack.go, website/docs/r/project_share_group.html.markdown, website/docs/r/service_github.html.markdown, website/docs/r/service_jira.html.markdown, website/docs/r/service_pipelines_email.html.markdown, website/docs/r/service_slack.html.markdown, website/gitlab.erb
=> Add resource for pipelines email integration

gitlab/provider.go, gitlab/resource_gitlab_project_level_mr_approvals.go, gitlab/resource_gitlab_project_level_mr_approvals_test.go, website/docs/r/project_level_mr_approvals.markdown, website/gitlab.erb
This MR adds a [Project-level MR approvals](https://docs.gitlab.com/ee/api/merge_request_approvals.html#project-level-mr-approvals) resource.
=> Add Project-level MR approvals

.github/workflows/release.yml
Oof. I screwed up and my attempt to cleanup a duplicate commit resulted in this file being removed: https://github.com/gitlabhq/terraform-provider-gitlab/pull/413
Apologies.
This reverts commit 0ee93b691f2708f436c0241c85ce455e8a759028.
=> Revert "Delete release.yml"

gitlab/resource_gitlab_project_mirror.go
=> gitlab_project_mirror: Mark URL as sensitive

docs/resources/deploy_token.md
I added a short line for the configuration of `expires_at` as per the code.
=> Documentation for `expires_at`

gitlab/resource_gitlab_project_membership.go
Similar to https://github.com/gitlabhq/terraform-provider-gitlab/pull/267
=> Do not fail when project member does not exist

gitlab/resource_gitlab_project.go
Increase from 1 minute to 10 minutes.
Fixes #528
=> Increase gitlab_project import timeout

docs/data-sources/users.md, docs/resources/user.md, gitlab/data_source_gitlab_user.go, gitlab/resource_gitlab_user.go, gitlab/resource_gitlab_user_test.go
As per subject. ~~I had to bump the `go-gitlab` dependency version~~. Nope, you already did! :-)
=> Support the Note field in the User resource/data

docs/resources/project.md
Tested to confirm that it does create a `main` branch by default
=> update reference to `master` branch to `main`

.github/workflows/markdown-lint.yml
...so that main branch builds to not fail unexpectedly after merging a PR from a fork.
=> CI: Run markdown linter on pull requests

gitlab/resource_gitlab_project_cluster.go, gitlab/resource_gitlab_project_cluster_test.go
fixes #617
Added a DiffSuppressFunc for the kubernetes_ca_cert attribute.
=> resource/gitlab_project_cluster: Suppress whitespace diffs for kubernetes_ca_cert attribute

docs/resources/project_membership.md
=> Fix GitLab project membership example

README.md
url was taken from https://www.terraform.io/logos.html
=> Fix Terraform logo

gitlab/resource_gitlab_project_test.go
This change adds a test case for creating a project without a README with `gitlab_project`. 
It also adds actual checks for the existing test cases to verify that a README is created when `initialize_with_readme = true`.
This was an attempt to reproduce #712 - however, it seems to work as expected.
=> Improve tests for initializing a project without README. Refs #712

gitlab/resource_gitlab_group_cluster.go, gitlab/resource_gitlab_group_cluster_test.go, gitlab/resource_gitlab_instance_cluster.go, gitlab/resource_gitlab_instance_cluster_test.go
=> instance_cluster/group_cluster: Suppress whitespace diff for kubernetes_ca_cert

docs/resources/service_microsoft_teams.md, gitlab/provider.go, gitlab/resource_gitlab_service_microsoft_teams.go, gitlab/resource_gitlab_service_microsoft_teams_test.go
This change adds the capability to manage the integration of GitLab with Microsoft Teams.
Fixes #308
=> Implement configuration of the integration "Microsoft Teams" (#308)

docs/data-sources/project_protected_branch.md, docs/data-sources/project_protected_branches.md, gitlab/data_source_gitlab_project_protected_branch.go, gitlab/data_source_gitlab_project_protected_branch_test.go, gitlab/data_source_gitlab_project_protected_branches.go, gitlab/data_source_gitlab_project_protected_branches_test.go, gitlab/resource_gitlab_branch_protection.go
This change set fixes the bugs introduced yesterday by merging #551. 
@nagyv
=> Fix bugs introduced with PR #551

docs/resources/group_ldap_link.md, docs/resources/group_membership.md, gitlab/util.go
=> Add minimal access level permissions

GNUmakefile, scripts/lint.sh
=> Add scripts to locally lint, like ci does

docs/resources/project.md, gitlab/resource_gitlab_project.go, gitlab/resource_gitlab_project_test.go
This change supersedes #604 and 
Closes #603
Closes #517
=> Support `issues_template` and `merge_requests_template` in project resource

gitlab/resource_gitlab_branch_protection.go, gitlab/resource_gitlab_deploy_token.go, gitlab/resource_gitlab_project_access_token.go, gitlab/resource_gitlab_project_approval_rule.go, go.mod, go.sum
=> Upgrade to go-gitlab v0.54.3. Closes #781

gitlab/provider_test.go, gitlab/resource_gitlab_group_variable_test.go
fixes #810 
There was a bug in one of the test checks. The provider code was correct.
=> Fix group variable test

.github/workflows/pr-target-opened.yml
A nice message welcoming new contributors and recommending the CONTRIBUTING.md.
When I tested this, the workflow was successful, but it did not recognize my test user as a new contributor, so I haven't actually seen it comment on a PR.
Message is:
```
Welcome @${{github.actor}} :wave:
It looks like this is your first submission to the [Terraform GitLab Provider](https://github.com/${{ github.repository }})! If you haven’t already done so, please make sure you have checked out our [CONTRIBUTING.md guide](https://github.com/${{ github.repository }}/blob/${{ github.event.repository.default_branch }}/CONTRIBUTING.md) to make sure your contribution has all the necessary elements in place for a successful approval.
Thanks again, and welcome to the community! :smiley:
```
- A \*.tf file for the …
=> Workflows: First interaction messsage on PRs

README.md
=> Change the default branch to main

docs/resources/project_hook.md, internal/provider/resource_gitlab_project_hook.go, internal/provider/resource_gitlab_project_hook_test.go
Added releases event option to project webhook resource and updated test and document
=> Added releases event webhook option

docs/resources/user.md, internal/provider/resource_gitlab_user.go, internal/provider/resource_gitlab_user_test.go
Just adding a basic implementation for blocking user in the terraform provider
closes #631
=> closes #631, adding the support to block users

docs/data-sources/projects.md, docs/resources/project.md, internal/provider/data_source_gitlab_projects.go, internal/provider/resource_gitlab_project.go, internal/provider/resource_gitlab_project_test.go
=> Implement `ci_forward_deployment_enabled`

internal/provider/resource_gitlab_group_ldap_link_test.go, internal/provider/testdata/resource_gitlab_group_ldap_link.json
=> Remove over-engineered testdata JSON file and just create the struct in the test

CHANGELOG.md
This is just a start and we can continue with it before the actual release.
=> Draft next release changelog

docs/resources/service_jira.md, internal/provider/resource_gitlab_service_jira.go, internal/provider/resource_gitlab_service_jira_test.go
Also mark `project_key` in docs as optional
=> feat: add api_url option for Jira service

internal/provider/data_source_gitlab_project_protected_branch.go, internal/provider/data_source_gitlab_project_protected_branches.go, internal/provider/resource_gitlab_branch_protection.go
I have to admit though that I kinda like the typed approach which was used there.
However, in favor of having compatible type assignments and consistency it probably makes sense to merge this.
=> Fix incompatible assignments for ResourceData.Set() reported by tfproviderlint. Closes #436

.github/workflows/pr-acceptance-ee.yml
=> Workflows: EE Permissions

.github/workflows/release.yml, .goreleaser.yml, terraform-registry-manifest.json
Check the changes if we update the release process as described in https://www.terraform.io/registry/providers/publishing
Closes https://github.com/gitlabhq/terraform-provider-gitlab/issues/896
- No new `//lintignore` comments were copied from existing code. (Linter rules are …
=> Fix the release process

docs/data-sources/group.md, docs/resources/group.md, go.mod, go.sum, internal/provider/data_source_gitlab_group.go, internal/provider/data_source_gitlab_group_test.go, internal/provider/resource_gitlab_group.go, internal/provider/resource_gitlab_group_test.go
=> Add prevent_forking_outside_group

CONTRIBUTING.md
=> docs: Update example link to not be broken

.github/workflows/stale.yml
Updates bot message to use correct number of days from the config.
=> Workflow: Fix stale message

internal/provider/resource_gitlab_deploy_token.go, internal/provider/resource_gitlab_deploy_token_test.go
This fixes an issue where resources get recreated in case there are more
tokens in a group or project then the page size.
I'm also going to implement a `GET /projects/:id/deploy_tokens/:deploy_token` API upstream in GitLab ...
=> resource/gitlab_deploy_token: Implement pagination when reading tokens

docs/resources/project_issue.md, internal/provider/resource_gitlab_project_issue.go
This change removes this colon rendering issue:
=> Fix docs rendering issue

internal/provider/resource_gitlab_pipeline_schedule.go
Getting rid of some more tech debt ...
=> resource/gitlab_pipeline_schedule: Use GET API to retrieve single resource instead of listing

internal/provider/resource_gitlab_project_variable.go, internal/provider/resource_gitlab_project_variable_test.go
=> resource/gitlab_project_variable: Use GET API to retrieve single resource instead of listing

docs/resources/group.md, internal/provider/resource_gitlab_group.go
=> resource/gitlab_group: document groups without parent group limitation on SaaS

.vscode/settings.json
I found these settings useful while trying out our gitpod.io integration. It allows you to run or debug any test by clicking the play button, rather than requiring you to use the terminal.
- No new `//lintignore` comments were copied from existing code. (Linter rules are meant to …
=> Add vscode settings for gitpod

scripts/healthcheck-and-setup.sh
=> Separating setup script from personal access token code

.gitignore, CONTRIBUTING.md, GNUmakefile, docker-compose.yml, scripts/gitlab.rb, scripts/healthcheck-and-setup.sh
=> Adding registry enablement fixes

docs/resources/project_badge.md, examples/resources/gitlab_project_badge/resource.tf, internal/provider/resource_gitlab_project_badge.go, internal/provider/resource_gitlab_project_badge_test.go
Closes #1053 
```
make testacc RUN=TestAccGitlabProjectBadge_basic
=== RUN   TestAccGitlabProjectBadge_basic
--- PASS: TestAccGitlabProjectBadge_basic (66.46s) …
```
=> add badge name

scripts/gitlab.rb
Needed to add an instance level test for #1049 
=> Add runner token to gitlab.rb

internal/provider/data_source_gitlab_projects.go, internal/provider/data_source_gitlab_projects_test.go
Simple fixes for a couple lint errors :)
Closes #437
Closes #435 
=> Fix lint errors

README.md
Adds details about the community meeting to the README
=> Add community hour details

internal/provider/data_source_gitlab_project.go, internal/provider/data_source_gitlab_projects.go, internal/provider/resource_gitlab_group_cluster_test.go, internal/provider/resource_gitlab_group_test.go, internal/provider/resource_gitlab_instance_cluster_test.go, internal/provider/resource_gitlab_pipeline_schedule_test.go, internal/provider/resource_gitlab_pipeline_schedule_variable_test.go, internal/provider/resource_gitlab_pipeline_trigger_test.go, internal/provider/resource_gitlab_project_cluster_test.go, internal/provider/resource_gitlab_project_freeze_period_test.go, internal/provider/resource_gitlab_project_level_mr_approvals_test.go, internal/provider/resource_gitlab_service_github_test.go, internal/provider/resource_gitlab_service_pipelines_email_test.go, internal/provider/resource_gitlab_service_slack_test.go, internal/provider/resource_gitlab_tag_protection_test.go
This change set addresses #434, #438 and #439 - which are all related to issues detected by the linter and specifically ignored by us in the past.
=> Remove a few technical debts regarding issues detected by the linter

CHANGELOG.md
Let's create a bug fix release v3.15.1, see #1124 
Closes #1124
=> Draft v3.15.1 changelog

docs/resources/project_membership.md, examples/resources/gitlab_project_membership/resource.tf, internal/provider/resource_gitlab_project_membership.go, internal/provider/resource_gitlab_project_membership_test.go
This PR closes https://github.com/gitlabhq/terraform-provider-gitlab/issues/1099
=> Add expiration date for gitlab_project_membership

scripts/gitlab.rb
See https://github.com/gitlabhq/terraform-provider-gitlab/pull/1128
=> Disable application settings cache for test instance

internal/provider/resource_gitlab_project.go, internal/provider/resource_gitlab_project_test.go
This bugfix resolves the issue described in #1127 where the project creation would timeout waiting for the default branch to be protected - but in the case where the default branch protection is disabled on instance-level this won't happen.
Closes: #1127
/cc @tschechniker
=> resource/gitlab_project: Fix project creation when default branch protection is disabled on instance-level

docs/data-sources/project.md, docs/data-sources/projects.md, docs/resources/project.md, internal/provider/data_source_gitlab_project.go, internal/provider/data_source_gitlab_projects.go, internal/provider/resource_gitlab_project.go, internal/provider/resource_gitlab_project_test.go
=> `gitlab_project`: Add `ci_default_git_depth` attribute

internal/provider/resource_gitlab_label_test.go, internal/provider/resource_gitlab_pipeline_trigger_test.go, internal/provider/resource_gitlab_project_hook_test.go, internal/provider/resource_gitlab_service_jira_test.go, internal/provider/resource_gitlab_service_slack_test.go
=> Refactor destory checks to check for resource under test

.github/workflows/pr-acceptance-ce.yml, .github/workflows/pr-acceptance-ee.yml, .github/workflows/push.yml, CHANGELOG.md, docs/resources/service_jira.md, internal/provider/resource_gitlab_service_jira.go, internal/provider/resource_gitlab_service_jira_test.go
A few days late, but better than never :)
=> Officially support GitLab 15.0, 15.1 and 15.2

docs/resources/project_protected_environment.md, internal/provider/resource_gitlab_project_protected_environment.go, internal/provider/resource_gitlab_project_protected_environment_test.go
=> resource/gitlab_project_protected_environment: Add docs that users and groups must be shared with the project

docs/resources/group_project_file_template.md, docs/resources/project.md, internal/provider/resource_gitlab_group_project_file_template.go, internal/provider/resource_gitlab_project.go
=> Update documentation for template resources

.github/workflows/pr-acceptance-ce.yml, .github/workflows/pr-acceptance-ee.yml, .github/workflows/push.yml, CHANGELOG.md
Upgrade to GitLab 15.3 in test matrix 🎉
=> Upgrade GitLab test matrix to 15.1, 15.2 and 15.3

CHANGELOG.md
Preparing the Changelog for [v3.17.0](https://github.com/gitlabhq/terraform-provider-gitlab/milestone/17) ...
=> Changelog for 3.17.0

.github/workflows/pr-acceptance-ce.yml, .github/workflows/pr-acceptance-ee.yml, .github/workflows/push.yml
These versions contain the SAML API fix and unblocks #1215 and v3.18.0
=> Upgrade to latest GitLab releases

.github/workflows/pr-acceptance-ce.yml, .github/workflows/pr-acceptance-ee.yml, .github/workflows/push.yml
=> Upgrade testing matrix to GitLab 15.3.3 to allow SAML tests

CHANGELOG.md
=> Draft changelog for 3.18.0

README.md
We've switched to meetup.com events.
=> Update community hours like

CONTRIBUTING.md, README.md
This PR adds a minor note to the CONTRIBUTING.md about the known issue with the m1 development evnrionment (and assumes the same is true of the m2 processor since it's likely an ARM issue).
I also took this opportunity to update the discord link in our README.md.
Closes #1299
- …
=> update CONTRIBUTING and README documentation

.github/workflows/pr-acceptance-ce.yml, .github/workflows/pr-acceptance-ee.yml, .github/workflows/push.yml
This PR just updates the test matrix to use the 3 most recent versions.
Closes #1301
=> Update text matrix for the 3 most recent versions
