gitlabhq/terraform-provider-gitlab

README.md

The clone source and destination should be in terms of
`terraform-providers` not `hashicorp`

Fix bad boilerplate in README

---

gitlab/config.go
gitlab/provider.go
website/docs/index.html.markdown

These settings can be used to configure the level of SSL verification
performed by the provider.
* `cacert_file` allows for the provision of an alternate ca cert, for
locally-signed or self-signed operations.
* `insecure` allows SSL verification to be turned off completely.  It is
not suggested as a first option.
Targets https://github.com/terraform-providers/terraform-provider-gitlab/issues/4

Add `cacert_file` and `insecure` options to the provider.

---

gitlab/provider.go
gitlab/resource_gitlab_label.go
gitlab/resource_gitlab_label_test.go
website/docs/r/label.html.markdown
website/gitlab.erb

new resource: gitlab_labels

---

gitlab/resource_gitlab_group.go
gitlab/resource_gitlab_group_test.go
vendor/github.com/xanzy/go-gitlab/groups.go
vendor/github.com/xanzy/go-gitlab/merge_requests.go
vendor/vendor.json
website/docs/r/group.html.markdown

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-gitlab	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccGitlabDeployKey_basic
--- PASS: TestAccGitlabDeployKey_basic (6.06s)
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (0.59s)
=== RUN   TestAccGitlabGroup_nested
--- FAIL: TestAccGitlabGroup_nested (0.93s)
testing.go:435: Step 2 error: Error applying: 1 error(s) occurred:
* gitlab_group.nested_foo: gitlab_group.nested_foo: diffs didn't match during apply. This is a bug with …
```

gitlab_group: support parent_id field

---

gitlab/resource_gitlab_project.go
website/docs/r/project.html.markdown

As noted in #35, when importing a project we were not updating the ID to
be the primary key id, so if a project was imported with `terraform
import gitlab_project.foo user/foo` it was kept in the state as
`user/foo` rather than the underlying id.
Here we fix that up, and add some documentation indicating that this
resource is importable (towards #36)

Fix and document importing projects

---

gitlab/resource_gitlab_group.go
website/docs/r/group.html.markdown

As noted in #35, when importing a group we were not updating the ID to
be the primary key id, so if a group was imported with `terraform
import gitlab_group.foo foo` it was kept in the state as
`foo` rather than the underlying id.
Here we fix that up, and add some documentation indicating that this
resource is importable (towards #36)
Closes #35, basically a copy of #37

Fix and document importing groups

---

gitlab/resource_gitlab_project.go

Updating the default branch caused the build to fail because it was inadvertently set to update the branch to the project description.
I attempted to write some tests for this case, but it's quite difficult. Gitlab returns `null` for the default branch until the first commit is pushed up to a repo, and the default branch can't be changed to another branch until that branch exists in Gitlab. However, by default, the `master` branch is the default branch when creating a new project. All makes sense, but, writing a test case means that a project needs to be created, the repo needs to exist and it needs to have multiple branches. I can help try and write it, but it's hard to fit it all into a single test step.

Fixes error when updating default branch

---

website/docs/r/group.html.markdown

It looks like a line of documentation in `gitlab_group` was taken from [`gitlab_project_hook`](https://github.com/terraform-providers/terraform-provider-gitlab/blob/3156239e4238a0b4803aa6bafeed8866fb50365d/website/docs/r/project_hook.html.markdown) when the docs were being written. I changed it to match the surrounding lines.

Fix group description in docs

---

gitlab/data_source_gitlab_project.go
gitlab/data_source_gitlab_user.go

1. **gitlab_project**
data parameters were not passed into terraform state, they are being set in `dataSourceGitlabProjectRead` but ignored if not in Schema
2. **gitlab_user**
`d.Set("userName"` needs to match Schema

fix: data resources

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

Hi,
This is a small fix for the shared_with_groups option in the project resource.
This makes `shared_with_groups` a TypeSet instead of TypeList in order to discard group list order and improve the plan.

Update project `shared_with_groups` option: change type to TypeSet

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
gitlab/util.go
website/docs/r/project.html.markdown

New options:
- merge_method
- only_allow_merge_if_pipeline_succeeds
- only_allow_merge_if_all_discussions_are_resolved

Add new options to project resource

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
website/docs/r/project.html.markdown

I ended up implementing this attribute because for some reason, when updating a simple field on a project, the `approvals_before_merge` key was sent in the JSON with a null value. I guess this showed up when updating the gitlab dependency. Either way, a new attribute :)
I left the tests with `0` that is the default because this feature is available under the Bronze tier. Calling the api to update the number will always return `0` in the community edition.

Add approvals_before_merge to Project

---

gitlab/provider.go
gitlab/resource_gitlab_project_cluster.go
gitlab/resource_gitlab_project_cluster_test.go

API Documentation: https://docs.gitlab.com/ee/api/project_clusters.html  
Solves #46 
```hcl
resource "gitlab_project" "foo" {
name = "foo-project-1"
}
resource gitlab_project_cluster "foo" {
project                       = "${gitlab_project.foo.id}"
name                          = "foo-cluster-1"
kubernetes_api_url            = "https://124.124.124"
kubernetes_token              = "some-token"
environment_scope             = "*"
kubernetes_ca_cert            = "some-cert"
kubernetes_namespace          = "changed-namespace"
kubernetes_authorization_type = "abac"
}
```
The documentation has not yet been added, since I would like to receive feedback first.
There is currently an issue with `enabled` field, which has been already reported to GitLab: …

Add support for gitlab project cluster

---

website/gitlab.erb

Two of the resources added in the latest release have incorrect labels in the documentation's navigation sidebar.

Fix incorrect link names in documentation.

---

gitlab/config.go

This makes debugging for developers & users of this provider easier by exposing all requests & responses in the log (when >`DEBUG` severity is set).
Example:
```
---[ REQUEST ]---------------------------------------
GET /api/v4/user HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: go-gitlab
Accept: application/json
Private-Token: ACCTEST
Accept-Encoding: gzip
-----------------------------------------------------
2019/02/23 00:47:49 [DEBUG] GitLab API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 714
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json
Date: Sat, 23 Feb 2019 00:47:49 GMT
Etag: W/"2fb3928e98d70dbe9e8fe1b09573eab8"
Server: nginx
Strict-Transport-Security: max-age=31536000 …
```

provider: Enable request/response logging

---

gitlab/resource_gitlab_deploy_key.go
gitlab/resource_gitlab_deploy_key_test.go
website/docs/r/deploy_key.html.markdown

Hi,
This PR allows importing deploy keys using the following syntax:
```
$ terraform import gitlab_deploy_key.test {project_id}:{deploy_key_id}
```
It includes acceptance test and doc update.
Best,

Allow Deploy Keys imports

---

gitlab/data_source_gitlab_user.go
gitlab/data_source_gitlab_user_test.go
website/docs/d/user.html.markdown

Hi,
This PR updates the *user* datasource.
It allows searching by id:
```hcl
data "gitlab_user" "foo" {
user_id = "2387"
}
```
It also adds more attributes and better handles the search parameters to avoid using multiple ones at the same time.
**Note**: the search by id parameter is called `user_id` because `id` is a Terraform reserved keyword. Same goes for the `provider` attribute renamed into `user_provider`. I'm willing to change this if you have better suggestions.
Best,

Update user datasource: allow searching by id and add attributes

---

website/docs/index.html.markdown

The site's markdown processor tries to automatically turn URLs into links, but this one
doesn't go anywhere, so let's style it as a code span.

website: make example server URL non-clickable

---

.travis.yml
gitlab/resource_gitlab_project_cluster_test.go
scripts/generate-access-token.rb
scripts/start-gitlab.sh

Fix acc tests

---

gitlab/resource_gitlab_project_cluster_test.go

Fixes #111 
Related: https://about.gitlab.com/2019/03/22/gitlab-11-9-released/#validate-kubernetes-ca-certificate-format

Fix project cluster acc test by adding a fake pem certificate

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
gitlab/util.go
website/docs/r/project.html.markdown

This PR adds `tags` attribute to project resource.
**NOTE**: Project update won't work due to internal service error mentioned here https://github.com/terraform-providers/terraform-provider-gitlab/pull/105

Add `tags` attribute for gitlab project

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
website/docs/r/project.html.markdown

Implemented the `container_registry_enabled` attribute for the `gitlab_project` resource.

add container_registry_enabled to project

---

gitlab/helper_test.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
scripts/generate-access-token.rb
scripts/start-gitlab.sh

Uses the *gitlab.Project struct and resource Schema to test the resulting values.
Removes the extra generate access token file and updates the access token value to be generated from a variable (with a default).

Cleans up "project" resource schema and testing framework

---

gitlab/resource_gitlab_project_cluster.go
gitlab/resource_gitlab_project_cluster_test.go
website/docs/r/project_cluster.html.markdown

This PR adds a new `domain` field to `project_cluster` resource.

Add domain to project cluster

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
website/docs/r/project.html.markdown

Add new flag to enable/disable shared runners in a project. This PR doesn't require any dependency updates.

Add shared_runners_enabled flag in project

---

gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_deploy_key.go
gitlab/resource_gitlab_group.go
gitlab/resource_gitlab_group_membership.go
gitlab/resource_gitlab_group_variable.go
gitlab/resource_gitlab_label.go
gitlab/resource_gitlab_pipeline_trigger.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_cluster.go
gitlab/resource_gitlab_project_hook.go
gitlab/resource_gitlab_project_membership.go
gitlab/resource_gitlab_project_variable.go
gitlab/resource_gitlab_service_slack.go
gitlab/resource_gitlab_tag_protection.go
gitlab/resource_gitlab_user.go

Stop silently deleting objects from state

---

gitlab/data_source_gitlab_group.go
gitlab/data_source_gitlab_group_test.go
gitlab/provider.go
gitlab/resource_gitlab_group.go
website/docs/d/group.html.markdown
website/docs/r/group.html.markdown
website/gitlab.erb

This PR adds a new data resource `gitlab_group`.
You can access GitLab group via `group_id` or `full_path`.
Fixes #103 
```hcl
data "gitlab_group" "foo1" {
full_path = "foo/bar"
}
```
```hcl
data "gitlab_group" "foo2" {
group_id = 123
}
```

Add GitLab Data Group

---

website/docs/r/group.html.markdown

The example incorrectly states the `namespace_id` key.

Fix documentation group to use parent_id

---

go.mod
go.sum
vendor/github.com/xanzy/go-gitlab/.gitignore
vendor/github.com/xanzy/go-gitlab/README.md
vendor/github.com/xanzy/go-gitlab/branches.go
vendor/github.com/xanzy/go-gitlab/event_types.go
vendor/github.com/xanzy/go-gitlab/gitlab.go
vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
vendor/github.com/xanzy/go-gitlab/project_clusters.go
vendor/github.com/xanzy/go-gitlab/project_import_export.go
vendor/github.com/xanzy/go-gitlab/projects.go
vendor/github.com/xanzy/go-gitlab/protected_tags.go
vendor/github.com/xanzy/go-gitlab/repositories.go
vendor/github.com/xanzy/go-gitlab/services.go
vendor/modules.txt

Hi,
This PR upgrades the `go-gitlab` dep to **v0.18.0**.
It is required for #101 since there're changes in fields' type of the Jira integration.
Thanks!

Upgrade go-gitlab dep from v0.17.0 to v0.18.0

---

gitlab/provider.go
gitlab/resource_gitlab_service_jira.go
gitlab/resource_gitlab_service_jira_test.go
gitlab/util.go
gitlab/util_test.go
go.mod
go.sum
vendor/github.com/xanzy/go-gitlab/.gitignore
vendor/github.com/xanzy/go-gitlab/README.md
vendor/github.com/xanzy/go-gitlab/branches.go
vendor/github.com/xanzy/go-gitlab/event_types.go
vendor/github.com/xanzy/go-gitlab/gitlab.go
vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
vendor/github.com/xanzy/go-gitlab/project_clusters.go
vendor/github.com/xanzy/go-gitlab/project_import_export.go
vendor/github.com/xanzy/go-gitlab/projects.go
vendor/github.com/xanzy/go-gitlab/protected_tags.go
vendor/github.com/xanzy/go-gitlab/repositories.go
vendor/github.com/xanzy/go-gitlab/services.go
vendor/modules.txt
website/docs/r/service_jira.html.markdown
website/gitlab.erb

Hi,
I'd like to add the Jira's integration implementation (see [doc.](https://docs.gitlab.com/ce/api/services.html#jira)).
Here's a sample of how it can be used:
```hcl
resource "gitlab_project" "awesome_project" {
name             = "awesome_project"
description      = "My awesome project."
visibility_level = "public"
}
resource "gitlab_service_jira" "jira" {
project  = "${gitlab_project.awesome_project.id}"
url      = "https://jira.example.com"
username = "user"
password = "mypass"
}
```
It includes documentation and acceptance tests.
**Note**: there's currently an issue with the `jira_issue_transition_id` parameter preventing it to work properly (see https://gitlab.com/gitlab-org/gitlab-ce/issues/55109). But the integration still can be used. I'll make the necessary updates to both …

Implement gitlab service jira

---

gitlab/resource_gitlab_service_jira.go

Hi,
This is a quick fix for #101 as requested by @roidelapluie that avoid deleting service from state on 404 errors since Gitlab makes no difference between 403 & 404 for security reasons.
Thanks,

Update Jira service: don't delete service from state on 404 errors

---

gitlab/provider.go
gitlab/resource_gitlab_pipeline_schedule.go
gitlab/resource_gitlab_pipeline_schedule_test.go
website/docs/r/pipeline_schedule.html.markdown
website/gitlab.erb

This PR implements a new resource `gitlab_pipeline_schedule`.
This depends on a fix in `go-gitlab`: xanzy/go-gitlab#607. Without this, the delete resource will always result in an error and Terraform will fail, even though the resource is deleted within Gitlab.
So I guess WIP until the above mentioned PR gets merged and `go-gitlab` gets updated in this project.

add gitlab_pipeline_schedule resource

---

gitlab/resource_gitlab_project_cluster.go
gitlab/resource_gitlab_project_cluster_test.go
website/docs/r/project_cluster.html.markdown

The gitlab api has a "managed" field to disable cluster management features when adding a kubernetes cluster. This implements that field. Default is true if you don't supply it.
This can only be toggled at cluster creation time, so changes will delete and readd the integration.
https://docs.gitlab.com/ee/api/project_clusters.html#add-existing-cluster-to-project
This also upgrades go-gitlab to an unreleased version that includes this field, which may be problematic.
I've run this fork for a few days successfully, and it has behaved as I expect it to.

Add support for managed clusters

---

gitlab/data_source_gitlab_project.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
website/docs/d/project.html.markdown
website/docs/r/project.html.markdown

Hallo, I'm proposing in this PR a few changes to enable the management of the `archived` attribute on both the `gitlab_project` resource and data source.
In doing so I had to implement partial state update in the project's update method, since the existing project properties update logic and the new archiving/unarchiving operation require different API calls, which may fail independently. 
In the process I also noticed that the existing code to handle the `shared_with_groups` attribute in the `gitlab_project` resource method does not seem to handle errors which are swallowed altogether. Since this attribute, just like the `archived` attribute, requires its own different API call, I expected it to use partial state updates in order to avoid an inconsistent state in case of failure.
I …

Implement the `archived` attribute on Project data source and resource 

---

gitlab/resource_gitlab_tag_protection.go
gitlab/resource_gitlab_tag_protection_test.go

When protecting a tag containing a wildcard (like v*), the terraform plugin generates an invalid URL and thus fails to protect it.
For example, the Terraform log contains:
2019/06/24 12:28:39 [DEBUG] read gitlab tag protection for project 38, tag v*
2019/06/24 12:28:39 [DEBUG] GitLab API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/v4/projects/38/protected_tags/v%252A HTTP/1.1
Host: 10.164.61.17
User-Agent: go-gitlab
Accept: application/json
Private-Token: nyPXE9zGT9aisyXvpWyG
Accept-Encoding: gzip
This is the REST call that checks if a protected tag has been correctly created, after the creation occurred. The URL is completely broken (it includes a double URL encoding). The GitLab server answers with a 404 return code.
Branches work correctly: …

Tag protection generates the wrong URL

---

website/docs/r/project_membership.html.markdown

fix documentation for gitlab_project_membership import, it's "groupid:user_id" use for import note username

docs(gitlab_project_membership): fix documentation

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

Currently, when defining a repository resource, the provider attempts to set a default branch even if the repository is empty (no branch).
Consider the following scenario:
1. Define a gitlab repository resource and set the default_branch attribute to "master"
2. Run terraform apply; terraform creates the repository, but gitlab sets the default branch to null, because the repository is empty (no branch has been created yet)
3. run again terraform apply; the terraform provider refreshes the project state and discovers that the default branch is set to null, while the resource description requires master. It tries to update the repository, setting the default branch; but the master branch does not exist, thus the operation fails.
With the changes in this pull request, the provider discards …

Do not enforce the default_branch in an empty repository

---

README.md

The readme lists a make command which doesn't exist

Fixed build command in README

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
website/docs/r/project.html.markdown

Resolves #177 - add `initialize_with_readme` attribute to project resource.
Not sure if we need additional acceptance tests here.

Add initialize_with_readme to project

---

gitlab/provider.go
gitlab/resource_gitlab_group_label.go
gitlab/resource_gitlab_group_label_test.go
website/docs/r/group_label.html.markdown
website/gitlab.erb

This MR adds a new resource `gitlab_group_label` to manage group labels.

Add gitlab_group_label resource

---

gitlab/resource_gitlab_pipeline_schedule.go

Terraform tries to do in-place update for `gitlab_pipeline_shedule.project`
```
~ resource "gitlab_pipeline_schedule" "schedule" {
active        = true
cron          = "0 1 * * *"
cron_timezone = "UTC"
description   = "test pipeline schedule"
id            = "38286"
~ project       = "14759476" -> "14689638"
ref           = "master"
}
```
However, this results in error `Error: PUT https://gitlab.com/api/v4/projects/14689638/pipeline_schedules/38286: 404 {message: 404 Pipeline Schedule Not Found}
` because the pipeline does not exist in the new project.
`ForceNew` fixes the issue.

fix: Set ForceNew for gitlab_pipeline_shedule.project

---

gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_branch_protection_test.go

The merge access level and push access level is not being mapped back to the textual forms in the state currently. This causes drift to not be detected by terrafrom refresh actions.
This fix uses the accessLevel map to translate the response from the API back to the format used by Terraform to store the state.

Fix state not being updated for gitlab_branch_protection

---

gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_label.go
gitlab/resource_gitlab_project_share_group.go

Make read callbacks graceful for project_share_group, branch_protection and label resources

---

gitlab/resource_gitlab_project_variable.go

Disabling `environment_scope` makes `gitlab_project_variable` only useful, if you are not differentiating between environments. Since a lot of use cases have multiple environments though, the current implementation is not very useful.
This PR fixes this known issue, by looking up variables with scope.
#213

fix: enable environment_scope of project variable loopkup

---

gitlab/resource_gitlab_group.go
gitlab/resource_gitlab_group_test.go

when a group was manually deleted, the read operation was throwing
an unrecoverable 404 error:
```
GET https://gitlab.com/api/v4/projects/16151185: 404 {message: 404 Project Not Found}
```
We should clear this from the state so that we can force recreation
of the group
```
▶ acctests gitlab TestAccGitlabGroup_
=== RUN   TestAccGitlabGroup_basic
--- PASS: TestAccGitlabGroup_basic (29.33s)
=== RUN   TestAccGitlabGroup_import
--- PASS: TestAccGitlabGroup_import (12.77s)
=== RUN   TestAccGitlabGroup_nested
--- PASS: TestAccGitlabGroup_nested (54.77s)
=== RUN   TestAccGitlabGroup_disappears
--- PASS: TestAccGitlabGroup_disappears (4.94s)
PASS
ok  	github.com/terraform-providers/terraform-provider-gitlab/gitlab	101.835s
```

Force recreate gitlab_group when not found on read

---

gitlab/resource_gitlab_service_slack.go
gitlab/resource_gitlab_service_slack_test.go
website/docs/r/service_slack.html.markdown

Currently, `notify_only_default_branches` is deprecated. `branches_to_be_notified` is the replacement. Everything is documented [here](https://docs.gitlab.com/ee/api/services.html#slack-notifications)
This PR deletes the first and creates the second.

Changing notify_only_default_branch for branches_to_be_notified on slack

---

go.mod
go.sum
vendor/github.com/xanzy/go-gitlab/.travis.yml
vendor/github.com/xanzy/go-gitlab/LICENSE
vendor/github.com/xanzy/go-gitlab/commits.go
vendor/github.com/xanzy/go-gitlab/deployments.go
vendor/github.com/xanzy/go-gitlab/event_parsing.go
vendor/github.com/xanzy/go-gitlab/event_systemhook_types.go
vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
vendor/github.com/xanzy/go-gitlab/gitlab.go
vendor/github.com/xanzy/go-gitlab/group_boards.go
vendor/github.com/xanzy/go-gitlab/group_hooks.go
vendor/github.com/xanzy/go-gitlab/group_members.go
vendor/github.com/xanzy/go-gitlab/group_variables.go
vendor/github.com/xanzy/go-gitlab/groups.go
vendor/github.com/xanzy/go-gitlab/issues.go
vendor/github.com/xanzy/go-gitlab/merge_request_approvals.go
vendor/github.com/xanzy/go-gitlab/merge_requests.go
vendor/github.com/xanzy/go-gitlab/pages_domains.go
vendor/github.com/xanzy/go-gitlab/pipelines.go
vendor/github.com/xanzy/go-gitlab/projects.go
vendor/github.com/xanzy/go-gitlab/runners.go
vendor/github.com/xanzy/go-gitlab/services.go
vendor/github.com/xanzy/go-gitlab/settings.go
vendor/github.com/xanzy/go-gitlab/users.go
vendor/modules.txt

Updates go-gitlab to v0.28.0
This update has some jira integration changes that i will create a followup PR on that will reduce spamming. Right now jira integration by default creates a jira comment for every commit back to the jira issue.

Update go-gitlab to v0.28.0

---

website/docs/r/group.html.markdown

This reverts commit 2573a0726bffb41ed0afec2152b6f9967bff5f89.
the resource has `namespace_id` when the data source uses `parent_id`. /cc @jakubknejzlik

Revert "Fix documentation group to use parent_id (#139)"

---

.github/workflows/acceptance-tests.yml

I've fixed up the acceptance tests, although I'm not sure if this is the right way to fix them.
The key thing here is that the GitLab personal access token must be 20 characters in length, otherwise it will not be treated as a PAT. Here are the relevant lines of code:
https://gitlab.com/gitlab-org/gitlab/blob/3174a1f5c5c317fef7c611f0363d1b00dc85f6fc/lib/gitlab/auth/auth_finders.rb#L138-176
It first tries to see if the token is an OAuth token. If the received token matches the PAT length, it will be treated as a PAT instead.
And here's where the PAT token length is defined: https://gitlab.com/gitlab-org/gitlab/blob/911f2085d95d2f35ed95e56da762d1e218e928e4/app/models/personal_access_token.rb#L11

Fix acceptance tests

---

go.mod
go.sum

go-gitlab v0.29.0 is required to support the soft-delete in Gitlab EE.

Update go-gitlab to v0.29.0

---

gitlab/resource_gitlab_service_jira.go
gitlab/resource_gitlab_service_jira_test.go
website/docs/r/service_jira.html.markdown

Relies on https://github.com/terraform-providers/terraform-provider-gitlab/pull/273 
The jira service has some extra flags that reduce the spamminess of the service.

Add jira flags

---

.github/workflows/acceptance-tests.yml

Using this pull request to check if the enterprise acceptance tests are disabled. The enterprise acceptance tests can't be run for pull requests because they depend on a Github Actions secret to decrypt the Gitlab Enterprise license file. This can only be done for protected branches in the repo itself.

Disable Enterprise acceptance tests for pull requests

---

gitlab/config.go

The default behaviour of `http.Transport` does not handle the use case of "many concurrent requests against a single host" very well.
By default, it will only keep 2 persistent connections in the pool. Everything above that is burst capacity, and those connections are closed. The result is a lot of connection churn, which can lead to port exhaustion (especially on more constrained resources like a shared NAT).
We (@gitlab) recently discovered this behaviour in a slightly different context, some analysis can be found in: [gitlab-org/gitlab-pages/-/merge_requests/274](https://gitlab.com/gitlab-org/gitlab-pages/-/merge_requests/274#note_335755221).
And we had a customer report who was experiencing that same issue with the gitlab terraform provider. So this patch is intended to provide the …

Increase MaxIdleConnsPerHost in http.Transport

---

gitlab/config.go
gitlab/provider.go
website/docs/index.html.markdown

This will allows the option to specify a client certificate and key
when your GitLab instance runs behind a proxy that requires both.

Provide a way to specify client cert and key

---

gitlab/provider.go
gitlab/resource_gitlab_group_ldap_link.go
gitlab/resource_gitlab_group_ldap_link_test.go
gitlab/testdata/resource_gitlab_group_ldap_link.json
website/docs/r/group_ldap_link.markdown

Adding new resource to manage group LDAP links

---

gitlab/resource_gitlab_group_label.go
gitlab/resource_gitlab_group_label_test.go

Update resource gitlab_group_label to read labels from all pages

---

gitlab/resource_gitlab_group_cluster.go
gitlab/resource_gitlab_group_cluster_test.go
gitlab/resource_gitlab_project_cluster.go
gitlab/resource_gitlab_project_cluster_test.go
website/docs/r/group_cluster.html.markdown
website/docs/r/project_cluster.html.markdown

Adds `management_project_id` as an option to Group and Project Clusters. 
Requires GitLab 12.10 
Option Documentation: https://docs.gitlab.com/ee/api/group_clusters.html#add-existing-cluster-to-group

Add management_project_id for Group and Project Clusters

---

GNUmakefile
gitlab/data_source_gitlab_projects.go
gitlab/data_source_gitlab_projects_test.go
gitlab/provider.go
go.mod
go.sum
vendor/github.com/mitchellh/hashstructure/LICENSE
vendor/github.com/mitchellh/hashstructure/README.md
vendor/github.com/mitchellh/hashstructure/go.mod
vendor/github.com/mitchellh/hashstructure/hashstructure.go
vendor/github.com/mitchellh/hashstructure/include.go
vendor/modules.txt
website/docs/d/projects.html.markdown
website/gitlab.erb

Picked up the work of https://github.com/terraform-providers/terraform-provider-gitlab/pull/161, as this is a critical missing datasource.
* Made group_id optional
* Use terraform-plugin-sdk
* Method refactoring here and there
Most credit goes to @enieuw and the original PR contributors.
**EDIT**: I ended up redoing everything after all, the datasource now supports fully all group and project listProject APIs parameters exposed by the go-gitlab package.

datasource: gitlab_projects

---

gitlab/provider.go
gitlab/resource_gitlab_deploy_token.go
gitlab/resource_gitlab_deploy_token_test.go
go.sum
website/docs/r/deploy_token.html.markdown

Fixes #107 plus group tokens.
Tests pass but marked as __WIP__ because of a couple of bugs from GitLab:
- [Deploy tokens API does not respect username inputs](https://gitlab.com/gitlab-org/gitlab/-/issues/211963)
- [POST /groups/:id/deploy_tokens requires expires_at](https://gitlab.com/gitlab-org/gitlab/-/issues/211878)
which create issues with the `username` and `expires_at` field respectively.
As soon as those are solved I'll remove a couple of TODOs and this should be fully working then.

Deploy token

---

gitlab/provider_test.go

I missed that isRunningEE was already moved

Fix duplicate `isRunningEE` function

---

gitlab/resource_gitlab_service_jira.go

I noticed this bug while trying to investigate a [possible flaky acceptance test](https://github.com/terraform-providers/terraform-provider-gitlab/pull/356/checks?check_run_id=834966420).
The bug is that if there is an error while creating or updating the Jira Service settings, the error is ignored.

Fix unhandled Jira Service error

---

gitlab/resource_gitlab_deploy_key.go
gitlab/resource_gitlab_pipeline_schedule.go
gitlab/resource_gitlab_pipeline_schedule_variable.go

I found a few places where there was the possibility of a panic if `response` was `nil`, which can happen if GitLab cannot be reached.
Also while I was there I removed some redundant status code checking, since the GitLab client library already treats the 204 code as a success.

Fix nil pointer dereferences during error handling

---

website/docs/r/group_cluster.html.markdown
website/docs/r/project_cluster.html.markdown

The correct argument to add a cluster management project is in fact `management_project_id` as per [the project_cluster](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_project_cluster.go#L94) and [group_cluster](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/resource_gitlab_group_cluster.go#L90) resource.

correct management_project_id argument in documentation

---

website/docs/r/project.html.markdown

This minor change corrects a mistake showing `master` as a valid level
of `group_access_level`.

Fix incorrect description of valid access levels

---

gitlab/resource_gitlab_group_label.go
gitlab/resource_gitlab_group_label_test.go
website/docs/r/group_label.html.markdown

This simply adds support for importing group labels, e.g.:
```sh
$ terraform import gitlab_deploy_key_enable.example 12345:fixme
```

Import group labels

---

gitlab/resource_gitlab_project_push_rules.go
gitlab/resource_gitlab_project_push_rules_test.go
website/docs/r/project_push_rules.html.markdown

This PR adds an importer to the `gitlab_project_push_rules` resource.
This closes #201, closes #239, and closes #352.
Note that I am not using the push rule resource ID as the import ID. I am instead using the project ID. The reason for this is that in practice, the project ID is the primary key. It's the only value used in the resource's Read function. I didn't want to change the resource ID because that would be a breaking change.
I've tested this import functionality using a local build and can verify that it works.

Add importer to resource_gitlab_project_push_rules

---

gitlab/resource_gitlab_label.go
gitlab/resource_gitlab_label_test.go
go.mod
go.sum
vendor/github.com/xanzy/go-gitlab/README.md
vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
vendor/github.com/xanzy/go-gitlab/gitlab.go
vendor/github.com/xanzy/go-gitlab/group_clusters.go
vendor/github.com/xanzy/go-gitlab/group_labels.go
vendor/github.com/xanzy/go-gitlab/group_members.go
vendor/github.com/xanzy/go-gitlab/group_milestones.go
vendor/github.com/xanzy/go-gitlab/groups.go
vendor/github.com/xanzy/go-gitlab/instance_clusters.go
vendor/github.com/xanzy/go-gitlab/issues_statistics.go
vendor/github.com/xanzy/go-gitlab/labels.go
vendor/github.com/xanzy/go-gitlab/license.go
vendor/github.com/xanzy/go-gitlab/project_mirror.go
vendor/github.com/xanzy/go-gitlab/project_snippets.go
vendor/github.com/xanzy/go-gitlab/projects.go
vendor/github.com/xanzy/go-gitlab/runners.go
vendor/github.com/xanzy/go-gitlab/services.go
vendor/github.com/xanzy/go-gitlab/users.go
vendor/modules.txt

Bump go-gitlab to v.0.34.1 
Needed to fix nested struct format in `gitlab/resource_gitlab_label.go`
Was failing with this error: 
gitlab/resource_gitlab_label.go:72:81: cannot use promoted field ListOptions.Page in struct literal of type gitlab.ListLabelsOptions
gitlab/resource_gitlab_label_test.go:106:80: cannot use promoted field ListOptions.PerPage in struct literal of type gitlab.ListLabelsOptions
because we weren't accessing the nested struct correctly.

Bump go-gitlab to v.0.34.1

---

CHANGELOG.md
README.md
gitlab/resource_gitlab_group_test.go
gitlab/resource_gitlab_service_github_test.go
go.mod
main.go
website/docs/r/service_github.html.markdown

Renamed the Github organization after the migration to https://github.com/gitlabhq
@nicholasklick @roidelapluie can you double-check whether I missed something? If not please merge ASAP.

Renamed the Github organization due to the migration

---

gitlab/helper_test.go
gitlab/provider_test.go

Several tests are only meant to run in Gitlab CE, so we were using a helper function `isRunningInEE` to detect the provider version and skip functions that only run in core and not in EE. We found that when running tests that use the `isRunningInEE` function, like `gitlab/resource_gitlab_service_github_test.go` and `gitlab/resource_gitlab_project_push_rules_test.go` , the test would fail because "Provider not initialized, unable to get GitLab connection". This is because when running single one-off tests, the provider is indeed not initialized, so `isRunningInEE` would not be able to find the provider nor the version in its metadata. Running single tests that relied on this function would fail, but running all the tests with `make testacc` would pass because the provider is initialized …

Fix isRunningInEE helper

---

website/gitlab.erb

It was missing from the index in the left side, and I almost started implementing it myself before finding it in the source code.

Documentation: Add group_ldap_link to index

---

gitlab/provider.go
gitlab/resource_gitlab_project_mirror.go
gitlab/resource_gitlab_project_mirror_test.go
website/docs/r/project_mirror.html.markdown
website/gitlab.erb

Implemented functionality for project mirrors, as per issue https://github.com/terraform-providers/terraform-provider-gitlab/issues/150
This was recently added to the go-gitlab library by myself and released in v0.33.0
https://github.com/xanzy/go-gitlab/pull/879

feature: add project mirror resources to provider

---

gitlab/resource_gitlab_user.go
gitlab/resource_gitlab_user_test.go

I imported an user into the terraform state and after I set the mandatory arguments the provider wanted to delete and recreate such user even if I didn't change anything.
This PRs maps the missing user attributes into the state.

Allow to change user email without recreating the resource

---

website/docs/r/group_cluster.html.markdown

Here is the same PR but from a forked Repo. Is this the correct workflow?
Added required quotes to the example for group_cluster.

Added Quotes in the example for group cluster

---

gitlab/resource_gitlab_project_push_rules.go
gitlab/resource_gitlab_project_push_rules_test.go

Closes #399 
Making this PR from a branch so that the EE acceptance tests run. This fixes the broken EE acceptance tests. I think the breakage got introduced originally while the EE license was expired and could not be tested.

Fix failing test TestAccGitlabProjectPushRules_import

---

gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_branch_protection_test.go
gitlab/util.go
website/docs/r/branch_protection.html.markdown

Closes #310 
I added an optional`code_owner_approval_required` argument to the existing `gitlab_branch_protection` resource.
GitLab doc for the feature here: https://docs.gitlab.com/ee/user/project/protected_branches.html#protected-branches-approval-by-code-owners-premium
Users who manage this setting out of band will see a diff in their plan after upgrading the plugin.

Add code_owner_approval_required argument to gitlab_branch_protection resource

---

gitlab/resource_gitlab_service_jira.go

Clean the state for jira if project doesn't exist

---

gitlab/resource_gitlab_project_level_mr_approvals.go

My apologies, I should have run the workflow for #356 in a branch to cover the new EE acceptance test, before merging. This should fix it. For CHANGELOG purposes we can consider this part of #356 and not a bugfix.

Fix incorrect type assertion in gitlab_project_level_mr_approvals

---

gitlab/resource_gitlab_project_level_mr_approvals.go

EE acceptance tests are still failing in master. This should be the last fix needed. This is to fix a bug in #356 where the `project_id` attribute was not set in `gitlab_project_level_mr_approvals` during read, because it was the wrong type.
As with #401 this does not need an entry in the Changelog since it is for a new resource.

Fix project_id not being set in gitlab_project_level_mr_approvals

---

gitlab/resource_gitlab_user.go
gitlab/resource_gitlab_user_test.go
website/docs/r/user.html.markdown

The documentation works when either `password` or `reset_password` is set.

Make password and reset_password exclusive

---

CHANGELOG.md
gitlab/resource_gitlab_group.go
website/docs/r/group.html.markdown

Reverts an [unreleased breaking change](https://github.com/gitlabhq/terraform-provider-gitlab/commit/01b429b0cbd42be21cad59167f8b2460f4282582#diff-ea50bce9f20ae93ae983c1f538a2d66bR64) as requested by @roidelapluie [here](https://github.com/gitlabhq/terraform-provider-gitlab/pull/362#discussion_r487260162). I also clarified the default behavior in the docs.

gitlab_group: Revert recent change to visibility_level attribute

---

gitlab/data_source_gitlab_project.go
gitlab/resource_gitlab_project.go
website/docs/d/project.html.markdown
website/docs/r/project.html.markdown

Add `path_with_namespace` to `gitlab_project` resource and data.

Add path_with_namespace to gitlab_project

---

gitlab/resource_gitlab_deploy_token.go
gitlab/resource_gitlab_project.go

Hi,
Now that Terraform SDK v2 is out, I scanned the codebase for deprecated v1 functions and found a few:
* `d.Partial`
* `d.SetPartial`
* `validation.ValidateRFC3339TimeString`
Removal notices for these functions here:
* https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#removal-of-helper-schema-resourcedata-setpartial
* https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#removal-of-deprecated-validation-functions
The removal of `Partial` and `SetPartial` from `gitlab_project` may look scary, but they're actually not adding anything to the resource behavior. Terraform performs a read before every operation to detect drift anyway. If for example in the `resourceGitlabProjectCreate` function project creation succeeds, but sharing it with groups fails, Terraform …

Fix Deprecated SDK Function Usage

---

gitlab/resource_gitlab_project_variable.go
gitlab/resource_gitlab_project_variable_test.go
gitlab/util.go
website/docs/r/project_variable.html.markdown

Supersedes  #324
Fixes #213
Fixes #195
Fixes #278
**tl;dr** I borrowed just the read function logic from #324 and added the `environment_scope` filter query to the update and delete functions.
This PR fixes a behavior where `gitlab_project_variable` resources for keys with multiple environment scopes were not reading data from a unique variable, but could read from any variable with the specified key, causing unexpected drift.
For users with the [feature flag on](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34490) or who are using [GitLab 13.4+](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/39209), this also lets them change environment scopes and remove variables with environment scopes, for `gitlab_project_variable` resources that have non-unique keys.
Note that one big …

gitlab_project_variable: fix nondeterministic reads when using environment_scope

---

.github/.goreleaser.yml
.github/workflows/release.yml

As taken from [terraform-provider-scaffolding](https://github.com/hashicorp/terraform-provider-scaffolding)
This workflow creates a draft release with all the required binary artifacts that the hashicorp registry requires. It requires an admin to set a github secret called GPG_PRIVATE_KEY which is the gpg  key with which the binaries will be signed
This workflow is a required step for achieving #411

import of release workflow from provider scafolding

---

docs/resources/project.md
gitlab/data_source_gitlab_projects.go
gitlab/helper_test.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_share_group.go
gitlab/resource_gitlab_project_share_group_test.go
gitlab/resource_gitlab_project_test.go

- resource/gitlab_project: remove `shared_with_groups` attribute
- resource/gitlab_project_share: fix update failing to change `access_level`
Part of #411 preparation
See discussion in #416 
Fixes #219

[Breaking] Fix gitlab_project and gitlab_project_share relationship

---

docs/data-sources/project.md
docs/resources/project.md
gitlab/data_source_gitlab_projects.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
go.mod
go.sum
vendor/github.com/xanzy/go-gitlab/client_options.go
vendor/github.com/xanzy/go-gitlab/commits.go
vendor/github.com/xanzy/go-gitlab/epics.go
vendor/github.com/xanzy/go-gitlab/gitlab.go
vendor/github.com/xanzy/go-gitlab/group_boards.go
vendor/github.com/xanzy/go-gitlab/group_milestones.go
vendor/github.com/xanzy/go-gitlab/groups.go
vendor/github.com/xanzy/go-gitlab/instance_clusters.go
vendor/github.com/xanzy/go-gitlab/instance_variables.go
vendor/github.com/xanzy/go-gitlab/issues.go
vendor/github.com/xanzy/go-gitlab/issues_statistics.go
vendor/github.com/xanzy/go-gitlab/merge_requests.go
vendor/github.com/xanzy/go-gitlab/milestones.go
vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
vendor/github.com/xanzy/go-gitlab/pipelines.go
vendor/github.com/xanzy/go-gitlab/project_members.go
vendor/github.com/xanzy/go-gitlab/projects.go
vendor/github.com/xanzy/go-gitlab/registry.go
vendor/github.com/xanzy/go-gitlab/services.go
vendor/github.com/xanzy/go-gitlab/tags.go
vendor/github.com/xanzy/go-gitlab/types.go
vendor/github.com/xanzy/go-gitlab/users.go
vendor/modules.txt

With [GitLab 13.3](https://about.gitlab.com/releases/2020/08/22/gitlab-13-3-released/) the packages feature is generally available.
This PR creates an argument `packages_enabled` based on the [GitLab API](https://docs.gitlab.com/ee/api/projects.html#create-project) field of the same name to control the activation of this feature.

Allow disable/enable packages repository

---

gitlab/resource_gitlab_group_membership.go

Same as discussed in #240: if the group member doesn't exist, then remove it from the state also.
Fixes #254

Do not fail when the group member does not exist

---

gitlab/resource_gitlab_project_mirror_test.go

This was caught by [staticcheck](https://staticcheck.io/), a component of [golangci-lint](https://golangci-lint.run/).
```
gitlab/resource_gitlab_project_mirror_test.go:117:4: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
return errors.New("unable to find mirror.")
^
```

Fix the mirror-exists check in the mirror test

---

docs/index.md

It's now considered bad form in Terraform to use interpolation with only variables and Terraform will raise a lint warning for it.

Remove old-style variable interpolation

---

gitlab/resource_gitlab_pipeline_schedule.go

Fixes #258
```
TF_LOG=TRACE terraform plan 2>&1 | grep 'GET /api/v4/projects/369/pipeline_schedules?'
2020-10-08T10:00:35.741+0300 [DEBUG] plugin.terraform-provider-gitlab_v3.0.0: GET /api/v4/projects/369/pipeline_schedules?page=1&per_page=20 HTTP/1.1
2020-10-08T10:00:36.098+0300 [DEBUG] plugin.terraform-provider-gitlab_v3.0.0: GET /api/v4/projects/369/pipeline_schedules?page=1&per_page=20 HTTP/1.1
2020-10-08T10:00:36.100+0300 [DEBUG] plugin.terraform-provider-gitlab_v3.0.0: GET /api/v4/projects/369/pipeline_schedules?page=2&per_page=20 HTTP/1.1
...
```

add pagination for ListPipelineSchedules

---

gitlab/config.go
gitlab/provider.go

Resolves https://github.com/gitlabhq/terraform-provider-gitlab/issues/450

Enable custom UserAgent

---

.github/workflows/acceptance-tests.yml
.github/workflows/unit-tests.yml

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
set-env is deprecating right now. So, we should update! :)

Update set-env github action command. 

---

docs/resources/project.md
gitlab/resource_gitlab_instance_cluster_test.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
gitlab/util.go

This allows to control the visibility of the Pages, see
https://docs.gitlab.com/ee/user/project/pages/pages_access_control.html
Closes: #471

feat(project): add the pages_access_level parameter

---

gitlab/resource_gitlab_user.go
gitlab/resource_gitlab_user_test.go

Fixes #469
The issue was a missing `nil` check.
An importer test was ignoring the `skip_confirmation` field, probably masking the bug.
Note I replaced the importer with `schema.ImportStatePassthrough` because the importer was duplicated code from the read function, and the read function only uses the `id` attribute to read. The three extra attribute-sets (lines 31-33) are covered already by `resourceGitlabUserSetToState`.

Fix nil pointer dereference importing gitlab_user

---

gitlab/resource_gitlab_project.go

This is a secret value and should be a `Sensitive` value.

Make the runners_token on the project secret

---

.github/workflows/acceptance-tests.yml
.github/workflows/unit-tests.yml

Fixes #493 
Unit and acceptance tests haven't been running since #484. Some misplaced quotation marks caused the variables to not be set, so the default Make target was being run in these workflows instead of the tests.
[Example](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#example-5)
Let's check that PRs created or rebased in the last week get this fix before they merge.
I opened an issue to look into the one acceptance test that is failing: #494

Fix unit and acceptance tests not running

---

docs/resources/instance_variable.html.markdown
gitlab/provider.go
gitlab/resource_gitlab_instance_variable.go
gitlab/resource_gitlab_instance_variable_test.go
vendor/github.com/xanzy/go-gitlab/gitlab.go

Closes #388. Supersedes https://github.com/terraform-providers/terraform-provider-gitlab/pull/1.
Awaits xanzy/go-gitlab#914. Automatic tests will definitely fail until that PR has been merged and released in a new version of the library.
Missing:

Support instance level CI variables

---

docs/resources/group_share_group.md
gitlab/provider.go
gitlab/resource_gitlab_group_share_group.go
gitlab/resource_gitlab_group_share_group_test.go

Follow-up from Pull Request review: https://github.com/gitlabhq/terraform-provider-gitlab/pull/369#pullrequestreview-487250800
Fixes #300
This will create a new resource `gitlab_group_share_group` to support sharing groups
Follows the pattern used by `gitlab_project_share_group`: https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_share_group

Add resource for group shared_with_groups

---

docs/resources/project.md
docs/resources/project_mirror.md
gitlab/data_source_gitlab_projects.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

Adds `mirror` and `mirror_trigger_builds` fields to Project
Related to Pull Request: https://github.com/gitlabhq/terraform-provider-gitlab/pull/449
Setup so EE tests can run against changes

Project mirroring

---

docs/resources/deploy_token.md
gitlab/resource_gitlab_deploy_token.go

These changes will fix the expiry behavior of deploy tokens.
Current state:
- Leaving `expires_at` at null in terraform results in the created token automatically being expired.
- Using an unrealistically high date as a workaround results in terraform segfaults, because gitlab internally sets them to never expire and the API will not return a valid date afterwards
Changes:
- Tokens will not expire per default, which makes more sense than creating an already expired Token
- Changes to the read behavior to check for `nil` before converting the date, as to not run into the terraform segfaults

fix deploy_token expiration

---

README.md

It's nice being able to click on those and getting redirected to the corresponding workflow.

Link badges in README to proper workflows

---

.gitignore
docs/resources/project_hook.md
gitlab/resource_gitlab_project_hook.go
gitlab/resource_gitlab_project_hook_test.go

Adds support for `push_events_branch_filter`, `confidential_issues_events` and `confidential_note_events` in `gitlab_project_hook` resource. See related issue #520.
Note that `deployment_events` is not yet supported in the currently vendored version of `go-gitlab`. Once #523 is merged I can prepare a separate PR for `deployment_events`.

support additional attributes in `gitlab_project_hook`

---

docs/data-sources/project.md
gitlab/data_source_gitlab_project.go
gitlab/data_source_gitlab_project_test.go

Allow `full_path` in addition to `id` in gitlab_project data source

---

gitlab/resource_gitlab_user.go
gitlab/resource_gitlab_user_test.go

Fixes #533 
I analyzed the test debug output and found that the problem was some inconsistency after a user is deleted.
I see `DELETE /api/v4/users/114 HTTP/1.1` return `HTTP/1.1 204 No Content`, and then later in the test during the destroy check, `GET /api/v4/users/114 HTTP/1.1` returns `HTTP/1.1 200 OK`.
This fix adds `WaitForState` to the `gitlab_user` delete function.

Check for state change on user delete

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

This should fix an issue where some push rules require GitLab premium.
Fixes #447

gitlab_project: Check each push rule individually

---

docs/resources/project.md
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

This adds support for setting mirror_overwrites_diverged_branches and only_mirror_protected_branches. Fixes #526.

Add optional mirror options

---

gitlab/resource_gitlab_group_share_group.go
gitlab/resource_gitlab_group_share_group_test.go

Related issue: https://github.com/gitlabhq/terraform-provider-gitlab/issues/524
Updates resource `gitlab_group_share_group`.  It only sets expires_at field when time is not nil.

Fix group_share_group nil pointer reference

---

.github/workflows/acceptance-tests.yml

In master, all acceptance tests are running against gitlab-ce. Problem was introduced in #535.

Fix EE tests actually running against CE

---

docker-compose.yml
scripts/await-healthy.sh

See https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume
I noticed that the Gitlab-license.txt file was being replaced by an empty directory of the same name, on my local machine. Changing the volume to an absolute path seems to have fixed it for my latest run.

Fix EE test mounting license as a directory

---

.github/workflows/acceptance-tests.yml

The acceptance-ee job is failing on the forked repo anytime someone makes a PR, which results in annoying notifications to the contributor. The fix is to only run the job if the repo is in the gitlabhq org.
I've verified that, with this fix, the job is enabled on pushes to this repo, but is disabled on forks.

Fix "Run failed" on forks

---

gitlab/resource_gitlab_deploy_token.go
gitlab/resource_gitlab_deploy_token_test.go

Fixes #522 by adding a `diffSuppressFunc` for `expires_at` attribute of resource `deploy_token` that compares the date strings as `time.Time`.

add diffSuppressFunc for 'expires_at' attribute in 'deploy_token'

---

docs/resources/pipeline_schedule.md
docs/resources/pipeline_trigger.md
gitlab/resource_gitlab_pipeline_schedule.go
gitlab/resource_gitlab_pipeline_schedule_test.go
gitlab/resource_gitlab_pipeline_trigger.go
gitlab/resource_gitlab_pipeline_trigger_test.go

```
make testacc-up
docker-compose up -d gitlab-ce
Creating network "terraform-provider-gitlab_default" with the default driver
Creating volume "terraform-provider-gitlab_config-ce" with default driver
Creating volume "terraform-provider-gitlab_logs-ce" with default driver
Creating volume "terraform-provider-gitlab_data-ce" with default driver
Creating volume "terraform-provider-gitlab_config-ee" with default driver
Creating volume "terraform-provider-gitlab_logs-ee" with default driver
Creating volume "terraform-provider-gitlab_data-ee" with default driver
Pulling gitlab-ce (gitlab/gitlab-ce:)...
latest: Pulling from gitlab/gitlab-ce
345e3491a907: Pull complete
57671312ef6f: Pull complete
5e9250ddb7d0: Pull complete
6e6d4ab7149b: Pull complete
0368f51f232f: Pull complete
12163d3ee437: …
```

Add support for importing Pipeline Schedules and Triggers

---

docs/resources/instance_variable.md

Looking on https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs gitlab_instance_variable is missing.
This patch should fix that situation by renaming the file and formatting the file to match the other documentations.

Missing documentation for gitlab_instance_variable

---

gitlab/resource_gitlab_project_test.go

This should resolve the error in acceptance tests:
```
=== RUN   TestAccGitlabProject_initializeWithReadme
testing.go:705: Step 0 error: Check failed: Check 2/2 error: got default branch "main"; want "master"
--- FAIL: TestAccGitlabProject_initializeWithReadme (17.06s)
```

fix: update default branch name to "main"

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
gitlab/util.go

This adds error handling to the `resourceGitlabProjectSetToState` function which used to call `Set` repeatedly without checking for errors.

chore: add error handling to resourceGitlabProjectSetToState

---

docs/resources/project_approval_rule.md
gitlab/resource_gitlab_project_approval_rule.go
gitlab/resource_gitlab_project_approval_rule_test.go

Carry #540 due to fork from wrong repo (just for my own sake).
Fixes #492.

Add protected_branch_ids to gitlab_project_approval_rule

---

.golangci.yml
errcheck_excludes.txt

The common case when using this method is to ignore the error return. This is because the Terraform test framework checks these errors for primitive types for us.
See https://www.terraform.io/docs/extend/best-practices/detecting-drift.html#error-checking-aggregate-types

golangci-lint: exclude ResourceData.Set

---

.github/workflows/golangci-lint.yml
gitlab/data_source_gitlab_group_test.go
gitlab/data_source_gitlab_projects.go
gitlab/data_source_gitlab_projects_test.go
gitlab/data_source_gitlab_user_test.go
gitlab/helper_test.go
gitlab/provider.go
gitlab/resource_gitlab_deploy_key_enable.go
gitlab/resource_gitlab_deploy_key_test.go
gitlab/resource_gitlab_group_ldap_link.go
gitlab/resource_gitlab_group_ldap_link_test.go
gitlab/resource_gitlab_group_membership_test.go
gitlab/resource_gitlab_group_variable_test.go
gitlab/resource_gitlab_pipeline_schedule.go
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_membership_test.go
gitlab/resource_gitlab_project_test.go

chore: run golangci-lint for pull requests and annotate failing checks so we can fix them individually, similarly to the tfproviderlint checks annotated in #653

Annotate golangci-lint failing checks

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go
gitlab/util.go

Fixes #349
Maintains the expected behavior from #299
Relates to #573 
- Made `default_branch` a computed attribute
- Removed the `DiffSuppressFunc` from `default_branch` so that we can use its value during creation
- Implemented logic to set the default branch in cases where a repository exists (if the project was created with a readme, as a mirror, or from a template)
- Refactored the mirror code to be more explicit, instead of calling the update function from inside the create function. There was an error being returned here, which was being ignored.

gitlab_project resource: make default_branch attribute configurable on create

---

docs/resources/project.md
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

This Merge Request aims to add a very simple change to the GitLab resource Project resource so that the CustomCIPath can be passed as a parameter to the Terraform resource
- Amend documentation to reflect the change
- Add a standalone acceptance test

Add CustomCIPath to resource `gitlab_project`

---

docs/resources/branch_protection.md
docs/resources/project_approval_rule.md
gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_branch_protection_test.go

Related to #659, this makes the `protected_branch_ids` argument of `gitlab_project_approval_rule` more useful by adding a computed `branch_protection_id` attribute to `gitlab_branch_protection`. It also fixes incorrect documentation.

New computed branch_protection_id attribute for gitlab_branch_protection

---

GNUmakefile
README.md
docs/index.md
gitlab/config.go
gitlab/provider.go
scripts/await-healthy.sh
scripts/healthcheck-and-setup.sh

Supersedes #678
Closes #60 
Thanks to @wuperry563 for the initial PR which this builds on.
As discussed in that PR, GitLab supports the same auth header for both PAT and OAuth. I've tested this change using a real PAT and it still works.

Support running the provider using an OAuth token

---

gitlab/resource_gitlab_deploy_token.go
gitlab/resource_gitlab_deploy_token_test.go

This Pull Request is the same as Allow to create deploy token with all possible scopes. #695 
The only difference is, that i removed write_repository, because it is not allowed

Added missing scopes to deploy token

---

docs/resources/project_level_mr_approvals.md

The only id in GitLab API for project MR approvals is project id.

Fix docs for gitlab_project_level_mr_approvals import

---

docs/resources/project_mirror.md
gitlab/resource_gitlab_project_mirror.go
gitlab/resource_gitlab_project_mirror_test.go

GitLab does not return username and password from the mirrors.
Therefore, let's ignore it in the provider.
Fix #504 

Do not recreate project mirror on every run.

---

docs/resources/group_badge.md
gitlab/provider.go
gitlab/resource_gitlab_group_badge.go
gitlab/resource_gitlab_group_badge_test.go

This adds support for group badges.

add support for gitlab group badges

---

docs/data-sources/project_protected_branch.md
docs/data-sources/project_protected_branches.md
gitlab/data_source_gitlab_project_protected_branch.go
gitlab/data_source_gitlab_project_protected_branch_test.go
gitlab/data_source_gitlab_project_protected_branches.go
gitlab/data_source_gitlab_project_protected_branches_test.go
gitlab/provider.go

Add data sources gitlab_project_protected_branch(es)

---

gitlab/helper_test.go
gitlab/resource_gitlab_project_mirror_test.go
gitlab/resource_gitlab_project_variable_test.go

Supersedes #538 (Cherry picked just the test refactor)
Relates to #205 (fixed for gitlab_project_mirror resource)
Relates to #434 (fixed for gitlab_project_mirror resource)
Move testAccGitlabProjectContext to helper_test.go and use it in resource_gitlab_project_mirror_test.go
This is a step toward having correct "destroy" tests for the provider.

Test refactor - testAccGitlabProjectContext and resource_gitlab_project_mirror_test.go

---

gitlab/resource_gitlab_user.go
gitlab/resource_gitlab_user_test.go

Follow-up on #490 @roidelapluie 
I looked at it again, and I don't think `skip_confirmation` should ever be set during reads or imports, since it is an attribute that only has effect during initial creation. ([API ref](https://docs.gitlab.com/ee/api/users.html))
This change should fix an issue where, if the resource is created with `skip_confirmation=false`, then when the user confirms their email, it would result in an unnecessary resource diff of `skip_confirmation=true`.

gitlab_user: Do not set skip_confirmation on read

---

docs/index.md
gitlab/config.go
gitlab/provider.go

This change adds a new `early_auth_check` flag to the provider configuration.
It defaults to `true` which causes the provider to perform a dummy request to the GitLab API to verify the
configuration. If that is not desired it can be set to `false` which avoids this call.
This can be in useful if the GitLab instance is created within the same terraform module as this provider
is being used.

Support `early_auth_check` flag in provider config. Closes #777

---

docs/resources/group_variable.md
gitlab/resource_gitlab_group_variable.go
gitlab/resource_gitlab_group_variable_test.go

Add support for `environment_scope` to group level variables
Fixes #610
Supersedes #611

Add environment scope to gitlab_group_variable

---

gitlab/data_source_gitlab_project.go
gitlab/data_source_gitlab_project_test.go

The problem with the `gitlab_project` data source was that if the id is a path with namespace and the reading of
the data source is delayed until `apply`, e.g. seeing something like
this:
```
<= data "gitlab_project" "some_project"  {
+ archived                         = (known after apply)
+ default_branch                   = (known after apply)
+ description                      = (known after apply)
+ http_url_to_repo                 = (known after apply)
+ id                               = "timo.furrer/some-project"
+ issues_enabled                   = (known after apply)
+ lfs_enabled                      = (known after apply)
+ merge_requests_enabled           = (known after apply)
+ name                             = (known after apply)
+ namespace_id                     = (known …
```

Properly allow arguments `id` or `path_with_namespace` for project data source

---

.github/workflows/release.yml
.github/workflows/test.yml

I had to find out what our .go-version file is for, since it isn't referenced anywhere. 😆
I assume it comes from Terraform, and [in their CI workflow](https://github.com/hashicorp/terraform/blob/main/.github/workflows/build.yml) they use it to set the Go version to build with. This PR aligns with that strategy.

Workflow: Read Go version from .go-version

---

tools/passes/apicovered/apicovered.go

Aghh, saw this right after hitting the merge button.

Fix issue in coverage tool

---

.github/workflows/pr-acceptance.yml

This is my last workflow-related PR, and it is a bug fix. 😛 
Minor annoyance. I saw workflow failures on my fork on the EE job, which was not supposed to run. It was due to a bug introduced in #426 where it does not check if the LICENSE_ENCRYPTION_PASSWORD is set, so the workflow would trigger anyway from the fork's main branch.
I copied this workflow code over from the `push.yml` one.
In the future we can probably de-duplicate some workflow config, but at the moment there are some bugs with workflow templating.
- https://github.community/t/support-for-yaml-anchors/16128
- https://github.community/t/ref-head-in-reusable-workflows/203690/66
- Create the …

Workflows: Fix issue where forks would still run EE tests

---

.github/labeler-pr-triage.yml
.github/workflows/pr-target.yml

closes #428 
New workflows for pull requests that automatically add `size/*` and other area-like labels to pull requests.

Workflows: Add triage labels to PRs

---

.github/workflows/milestone-closed.yml

If we continue using milestones, this workflow would automatically comment on issues and PRs after we release, notifying watchers.

Workflow: Comment on closed issues/PRs with a milestone when the milestone is closed

---

.github/labeler-issue-triage.yml
.github/workflows/issue-comment-created.yml
.github/workflows/issue-opened.yml
.github/workflows/issue-or-pr-closed.yml
.github/workflows/stale.yml

Adds workflows for:
- Marking issues and PRs as "stale" and then closing them after 2 weeks
- Adding "needs-triage" and conditionally "bug" labels (based on a regex) for newly opened issues
- Unmarking issues as "stale" or "waiting-response" whenever there is activity
- Removing labels "waiting-response" or "needs-triage" if an issue is closed with those labels
Note that I configured the stale workflow to never close an issue with a "bug", "enhancement", or "keep-open" label.
I tested most of this in my fork, but I have not tested the cron job workflow. It is copied from the action documentation, so it should work.
- Update the …

Workflows: Label stale issues and PRs, and issue triage labels

---

examples/gitlab-managed-state/README.md

Fixes missing line continuation in the example `terraform init` command in the GitLab managed state README.

Add missing line continuation in example terraform init command

---

docs/resources/project.md
gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

This change implements an `archive_on_destroy` attribute on the
`gitlab_project` resource. It defaults to `false`, if set to `true`, on
a destroy it will *archive* the project instead of deleting it.
This is especially useful in organizations where repositories need to
be kept for regulatory purposes and can't be deleted.
PS: the diff is a mess: I've basically just `if'ed` the `DeleteProject` case depending on the `archive_on_destroy` attribute and called `ArchiveProject` in the new branch :)

Implement `archive_on_destroy` attribute for projects. Closes #761

---

docs/resources/branch_protection.md
docs/resources/group_ldap_link.md
docs/resources/group_membership.md
docs/resources/group_share_group.md
docs/resources/project_membership.md
docs/resources/project_share_group.md
docs/resources/tag_protection.md
examples/resources/gitlab_group_ldap_link/resource.tf
examples/resources/gitlab_project_share_group/resource.tf
gitlab/access_level_helpers.go
gitlab/data_source_gitlab_group_membership.go
gitlab/data_source_gitlab_project_protected_branch.go
gitlab/resource_gitlab_branch_protection.go
gitlab/resource_gitlab_branch_protection_test.go
gitlab/resource_gitlab_group_ldap_link.go
gitlab/resource_gitlab_group_ldap_link_test.go
gitlab/resource_gitlab_group_membership.go
gitlab/resource_gitlab_group_membership_test.go
gitlab/resource_gitlab_group_share_group.go
gitlab/resource_gitlab_project_membership.go
gitlab/resource_gitlab_project_membership_test.go
gitlab/resource_gitlab_project_share_group.go
gitlab/resource_gitlab_project_share_group_test.go
gitlab/resource_gitlab_tag_protection.go
gitlab/resource_gitlab_tag_protection_test.go
gitlab/util.go
gitlab/util_test.go

The situation is a little more trickier than I've expected.
See my comments in `gitlab/access_level_helpers.go`.
I think that this should be a good enough first improvement and makes
some helpful clarifications in the docs. It also aligns API attributes
in the `gitlab_group_ldap_link` and `gitlab_project_share_group`
resources. The latter even includes a state migration to ensure
compatibility with older states.
Closes #794

Aligns the *Access Level* situation in this providers with the upstream API. Closes #794

---

docs/resources/service_slack.md
gitlab/resource_gitlab_service_slack.go
gitlab/resource_gitlab_service_slack_test.go

This is a start towards correctly implementing the Slack Notification
Integration Service. When I started I wasn't aware of the problems in
the upstream GitLab API and the misalignment between `go-gitlab` and the
upstream GitLab API (maybe by intention because the upstream API is broken).
Long story short, there is a GitLab upstream issue here:
* https://gitlab.com/gitlab-org/gitlab/-/issues/28903
a go-gitlab issue here:
* https://github.com/xanzy/go-gitlab/issues/1354
And we have one here:
* https://github.com/gitlabhq/terraform-provider-gitlab/issues/790
Nevertheless, I think we should merge this change set. It uses the pass
through importer for the resource and also cleans up a few things. In
addition I've aligned the resource schema with the upstream API and
commented out the missing …

resource/service_slack: use pass through importer and start alignment with upstream API. Refs #790

---

.github/workflows/pr-required-labels.yml

This action fails if either `needs-rebase` or `do-not-merge` labels are present on the PR.
The benefit is we have a way to communicate that a PR should not be merged (`do-not-merge`) that has some enforcement with it.
I don't know how useful this is right now, but we can also expound on it to add other label rules, for example a PR must have one of N different labels before it can be merged. It could be useful for PR triaging purposes.

Workflows: Prevent merging PRs with needs-rebase or do-not-merge labels

---

.github/workflows/pr-check-conflicts.yml

Automatically adds and removes the `merge-conflict` label based on whether the PR has merge conflicts.
Action docs: https://github.com/marketplace/actions/label-conflicting-pull-requests
I configured it to comment on the PRs, but we can turn that off if it's too noisy.

Workflows: Automate applying merge-conflict label

---

.github/workflows/stale.yml

Some minor adjustments based on early feedback to the stale workflow.
- Increase inactivity time from 90 days to 120 days
- Increase time before closing issue from 14 days to 30 days
- Add `documentation` as another label which can prevent an issue from being stale (idea being that for now we don't make an issue stale if it fits into a triage status that we are able to act upon)
- Minor tweaking of language in the message to be more positive by encouraging new information in the case of an issue, and regular PR hygiene in the case of a PR.
I'd like it if we could merge this before the next batch goes out today. 😄 
- Update the …

Workflows: stale adjustment

---

CHANGELOG.md
gitlab/data_source_gitlab_user.go
go.mod

fixes #841 
We do not have a `created_at` attribute on the `gitlab_user` resource; only the data-source.
I'm not sure why the panic was not caught in our tests, but I assume it has to do with how we create the users in the test. The stack trace in the bug report made this bug very obvious, so I'm confident in the change regardless.
@nagyv Could you release a patch after merging this please? (This is a regression in 3.9.0 resulting from #725)

Fix gitlab_user datasource crash

---

docs/data-sources/user.md
gitlab/data_source_gitlab_user.go
gitlab/data_source_gitlab_users.go

Refs #839
see https://gitlab.com/gitlab-org/gitlab/-/commit/eb4d94f44a42848dcaffd4afd499b8559d1b3d4e
which contains a change to lookup the user by its public email address instead of the primary one.

datasource/gitlab_user(s): aligned email description with upstream API. Refs #839

---

gitlab/resource_gitlab_project.go
gitlab/resource_gitlab_project_test.go

This is a possible approach to fix https://github.com/gitlabhq/terraform-provider-gitlab/issues/836. Even though, I am not sure if that is
really that elegant of a solution ...
The root problem here is that the SDK v2 doesn't support to check if an
attribute value was set in config, state or the plan. During creation of
push rules, we don't have a way to distinguish between the default and
if the user has set the default explicitly. This makes the behavior
working for all cases (AFAIK) (incl. changing the instance default push
rules, no automated test possible yet).
This will be possbile in the new terraform provider framework

resource/gitlab_project: correctly handle push rules add and edit

---

.github/workflows/issue-comment-created.yml
.github/workflows/issue-opened.yml

Fixed some annoyances fighting with automation over labels.
- Issues opened by collaborators now won't get labels added (e.g. "needs-triage")
- Comments from collaborators now won't cause labels to be removed (e.g. "waiting-response")
Tested in my fork 👍 

Workflows: Disable triage labels for collaborators

---

internal/provider/data_source_gitlab_projects.go
internal/provider/data_source_gitlab_projects_test.go

This change makes use of the deprecated `d.GetOkExists()` function to
check if a boolean attribute has been set by the user or not.
AFAIK, it's the only way to achieve that in the SDK v2. It doesn't seem
to go anywhere without a proper replacement.
See:
* https://github.com/hashicorp/terraform-plugin-sdk/issues/817
* https://github.com/hashicorp/terraform-plugin-sdk/pull/350#issuecomment-597888969
Closes #452

datasource/gitlab_projects: Allow to get archived and unarchived repositories. Closes #452

---

internal/provider/resource_gitlab_group.go
internal/provider/resource_gitlab_group_test.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

This change includes what is in #760 from @switchboardOp, but adds an acceptance tests.
I also had to fix the `gitlab_group` resource to support groups setting the default branch protection to `0`.
Closes #759 
Closes #760

Support creating project in group without default branch protection

---

internal/provider/resource_gitlab_project.go

This fixes an issue where branch protection ran in the background when creating a project, causing the default branch to occasionally not be protected.
Closes #800 
There was a race condition apparent in project creation where occasionally the branch protection would return `false` even though the branch had been protected asynchronously. This could cause issues if downstream resources used that output value. This also caused several tests that checked the branch protection status to be flakey and seemingly appear to fail rendomly when they were, in fact, failing properly.

resolves #800: Add WaitForState support for resource_gitlab_project branch protection

---

internal/provider/environment_scope_helper.go
internal/provider/resource_gitlab_group_variable.go
internal/provider/resource_gitlab_group_variable_test.go
internal/provider/resource_gitlab_project_variable.go

It's currently sporadically failing, because of the upstream bug here: https://gitlab.com/gitlab-org/gitlab/-/issues/333296
I've also refactored the `withEnvironmentScopeFilter` function into a separate file.

Add failing group variable update test to test issue #861

---

docs/resources/project.md
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

…
I gotta admit that I'm not support happy with the implementation,
nor the approach in general.
However, I think we agree that it's best to not break backwards
compatiblity as first priority.
In any case, we have #550 to discuss that :)
Closes #770
Closes #776

resource/gitlab_project: fix backwards-compatibility with 14.1 regarding the `squash_option`. Closes #770

---

docs/resources/group_ldap_link.md
examples/resources/gitlab_group_ldap_link/import.sh

This is very unsatisfying, because I don't see a reason that the resource couldn't support import.
However, I suspect a necessary incompatibility there - I'll open another issue -> #869.
Closes #448

resource/gitlab_group_ldap_link: remove doc for import, because it is not supported

---

docs/data-sources/project.md
docs/resources/project.md
examples/gitlab-managed-state/main.tf
internal/provider/data_source_gitlab_project.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

As mentioned on #782, the field is available on GitLab but still not
possible to use on terraform
Reference:
- https://github.com/gitlabhq/terraform-provider-gitlab/issues/782

Add printing_merge_request_link_enabled attribute to projects

---

internal/provider/resource_gitlab_group_ldap_link.go
internal/provider/resource_gitlab_group_ldap_link_test.go

Refs: #771 
@armsnyder do you know anything about that `force` flag? And how it's supposed to work?
The test currently is failing (it was never executed, so we didn't notice) and it's apparent why, but I don't see what the intention was and how to make it "work" again :D

Fix gitlab_group_ldap_link panic on group_access attribute and re-enable tests

---

docs/resources/branch_protection.md
examples/resources/gitlab_branch_protection/resource.tf
internal/provider/resource_gitlab_branch_protection.go
internal/provider/resource_gitlab_branch_protection_test.go

Issue 709 requested the `allow_force_push` option to be added to the branch protection resource.  These changes add that feature, along with the appropriate tests.  The API does not support updating the allow force push configuration, so any changes will force a new resource to be created.
Closes #709 .  Adds `allow_force_push` attribute to branch protection resource.

Add branch protection support for allow_force_push

---

internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

All project attributes which are affected by a namespace or path change are re-computed if changed and dependent resources on those attributes will be updated in the same run.
Closes: #874

[gitlab_project] re-compute project attributes if path or namespace changed

---

.github/workflows/pr-required-labels.yml

Since EE tests do not run by default, this will prevent us (mostly me, I'm bad) from merging a PR accidentally that has not had EE tests run, or explicitly ignored with "skip-ee-test".
- No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be …

Workflows: Require PRs to have "safe to test" or "skip-ee-test" label before merging

---

docs/resources/group_ldap_link.md
examples/resources/gitlab_group_ldap_link/import.sh
internal/provider/resource_gitlab_group_ldap_link.go
internal/provider/resource_gitlab_group_ldap_link_test.go

**Why**
There is a bug that [the doc](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group_ldap_link#import) says we can use `terraform import`, but actually the function is not implemented
**Code Changes**
* Added the missing import function and acceptance test case
* ~Fixed a bug to set `access_level` instead of `group_access`, because `access_level` is the one defined in schema~
* ~Assigned the correct string value to `group_access`, before is an int type~, already fixed in the latest main branch
* Set `force=false` as default when importing, because we can not get any value from the Gitlab API
* Updated the doc about import part
**Design Changes**
* Added `group_id` in the import id string to change it from `ldap_provider:cn` to …

fix(group_ldap_link): add missing terraform import feature for group LDAP link

---

CHANGELOG.md
internal/provider/resource_gitlab_branch_protection.go

I don't really understand yet what happens here. However, that behavior
changed from v3.9.1 to v3.10.0. Thus, I'm simply reverting it back.
We've had a brief exchange about this already when the "broken" code was
merged here: https://github.com/gitlabhq/terraform-provider-gitlab/pull/881#discussion_r812109889
Obviously, we made the wrong call in that this situation doesn't
happen ... well, it happened.
Looking at the `gitlab_branch_protection` resource I find that it's
kinda unclear what's going on, also looking at the upstream API docs
doesn't shed any lights on this as the documentation is quite sparse.
Some of this was lately raised by @beekeep in
https://github.com/gitlabhq/terraform-provider-gitlab/issues/878#issuecomment-1048902570
, that is that some fields are arguments in the …

resource/gitlab_branch_protection: fix issue claiming that no valid access level can be found. Closes #890

---

docs/resources/project_level_mr_approvals.md
internal/provider/resource_gitlab_project_level_mr_approvals.go
internal/provider/resource_gitlab_project_level_mr_approvals_test.go

Adds `require_password_to_approve` argument to `gitlab_project_level_mr_approvals` resource.
Follow-up for xanzy/go-gitlab#1116

Add require_password_to_approve option for MRs

---

docs/resources/user.md
internal/provider/resource_gitlab_user.go
internal/provider/resource_gitlab_user_test.go

This change will fix a regression from v3.9.0 to v3.10.0, see report in #897.
However, the regression is just because the user state has been changed outside of terraform, while it was supposed to be owner by terraform. It was changed outside of terraform, because the `gitlab_user` resource didn't support deactivating users.
Therefore, we could argue that this is actually a new feature and not a bug fix. But whatever, @ilpianista how urgent is the upgrade to 3.10 for you?

resource/gitlab_user: Add support for `deactivated` user state. Closes #897

---

internal/provider/resource_gitlab_group_badge.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_badge.go

This change fixes the read function of the following resources to properly handle out of bound deletions:
- `gitlab_project` 
- `gitlab_project_badge`
- `gitlab_group_badge`
In case a resource is deleted outside of terraform the tf state drift and we need to remove it if the read function received a `404`.
@armsnyder any ideas for how to test this in a non-hacky way?

Correctly handle deletion outside of terraform

---

CHANGELOG.md

See the [v3.12.0 milestone](https://github.com/gitlabhq/terraform-provider-gitlab/milestone/9)
Most prominently we missing:
I consider #891 to be optional, but if possible, let's release it, too ;)

Changelog for v3.12.0

---

.github/workflows/pr-lint.yml
.github/workflows/push.yml
GNUmakefile
docs/data-sources/project_issue.md
docs/data-sources/project_issues.md
docs/data-sources/project_tag.md
docs/resources/group.md
docs/resources/project_issue.md
docs/resources/project_tag.md
internal/provider/data_source_gitlab_project_issue.go
internal/provider/data_source_gitlab_project_issues.go
internal/provider/data_source_gitlab_project_tag.go
internal/provider/resource_gitlab_group.go
internal/provider/resource_gitlab_project_issue.go
internal/provider/resource_gitlab_project_tag.go
scripts/lint-custom.sh

Added a new CI job and make target `make lint-custom` to run a shell script that performs miscellaneous additional linter automation that can't fit into an existing lint framework.
Added one custom linter that greps the generated documentation and outputs an error for any pages that are missing a link to upstream GitLab documentation.
The linter script uses the [::error](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) command in order to annotate the PR files with the error message.
Here's what the errors look like in a PR:
- …

Workflows: Lint docs for upstream API link

---

docs/resources/branch_protection.md
examples/resources/gitlab_branch_protection/resource.tf
internal/provider/access_level_helpers.go
internal/provider/resource_gitlab_branch_protection.go
internal/provider/resource_gitlab_branch_protection_test.go

Closes #878.
Adds `unprotect_access_level` and `allowed_to_unprotect` attributes to the branch protection resource, which should bring the resource in line with the API.  Also changes `merge_access_level` and `push_access_level` to optional, as they were previously marked as required, but they are not required in the API.  A default is also configured, to match the default that is set via the API.
- New …

Add `allowed_to_unprotect` and `unprotect_access_level` fields to branch protection

---

docker-compose.yml

The 'Z' option tells Docker to label the content with a private unshared
label. This fixes running healtcheck-and-setup on SELinux distros
(RedHat, Fedora, CentOS). Without the flag, SELinux prevents any access
to the file.
- No new `//lintignore` comments were copied from …

Add SELinux Z flag to docker bind

---

docs/resources/deploy_token.md
docs/resources/project_access_token.md
docs/resources/project_hook.md
examples/resources/gitlab_deploy_token/import.sh
examples/resources/gitlab_project_access_token/import.sh
examples/resources/gitlab_project_hook/import.sh
internal/provider/resource_gitlab_deploy_token.go
internal/provider/resource_gitlab_deploy_token_test.go
internal/provider/resource_gitlab_group_ldap_link.go
internal/provider/resource_gitlab_project_access_token.go
internal/provider/resource_gitlab_project_access_token_test.go
internal/provider/resource_gitlab_project_hook.go
internal/provider/resource_gitlab_project_hook_test.go

This change set together with (https://github.com/gitlabhq/terraform-provider-gitlab/pull/954) implements all missing importers and therefore closes the long open #36 .
I've focused on the importer themselves and not so much about the underlying ids. 
I'll follow up with an issue describing the current state of resource ids currently in use. I hope that we can streamline those for v4 of the provider ...

Implement all missing importers

---

.github/workflows/pr-acceptance-ee.yml
.github/workflows/pr-required-labels.yml

Addresses an issue where EE tests only run when the `safe to test` label is added by returning to the previous behavior of running EE tests on all pushes to a PR.
I'm opening this as an alternative to #898 which I believe is now feasible since #902 was merged.
- No new …

Workflows: Run EE tests on PRs without label requirement

---

docs/resources/label.md
examples/resources/gitlab_label/import.sh
internal/provider/resource_gitlab_group_label.go
internal/provider/resource_gitlab_group_label_test.go
internal/provider/resource_gitlab_label.go
internal/provider/resource_gitlab_label_test.go

Removing some tech debt to use specific resources GET API instead of the list API...
Also implementing the missing `gitlab_label` importer (#36) and removing some unnecessary large testing configurations.

Use specific GET API instead of list for labels

---

go.mod
go.sum
internal/provider/data_source_gitlab_project_issues.go
internal/provider/resource_gitlab_project_approval_rule.go

This fixes a potential bug that the resource is marked for destroy after a read,
because it was not found on the first page. Pagination was not implemented.
However, there exist a specific API to get a single project-level approval rule.
I have implemented it in go-gitlab:
* https://github.com/xanzy/go-gitlab/pull/1410
After it is released, we should be able to just rebase and LGTM ;)
Refs: #949

resource/gitlab_project_approval_rule: fix potential accidental destroy of resource if not in first page

---

docs/resources/managed_license.md
examples/resources/gitlab_managed_license/resource.tf
internal/provider/helper_test.go
internal/provider/resource_gitlab_managed_license.go
internal/provider/resource_gitlab_managed_license_test.go

Update managed_license resources to deprecate existing values and add GitLab 15+ values

---

docs/resources/repository_file.md
internal/provider/resource_gitlab_repository_file.go
internal/provider/resource_gitlab_repository_file_test.go
internal/provider/util.go

This change set implements the following two measures to mitigate / remove the parallelism issues we were having as described in #940:
1. only allow a single `gitlab_repository_file` resource to make an API call (no matter to which project or file)
1. retry API calls in case of a refresh error
The first mitigates that resources within an apply / destroy are queued and the second mitigates the case when something else outside of terraform changes the repository state. Both combined are good mitigations for the issue at hand.
The drawback of this change is that it'll slow down certain terraform configurations - necessarily and unnecessarily in cases were a files in different repositories / projects are changed, but still queued. I think that's a limitation I'm willing to take for the …

resource/gitlab_repository_file: Mitigate parallelism limitation 

---

internal/provider/resource_gitlab_project.go

This avoids a subsequent non-empty plan to a minial `gitlab_project` configuration:
```
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
~ resource "gitlab_project" "test" {
id                                               = "481"
name                                             = "Test 3"
tags                                             = []
+ topics                                           = []
}
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```
This behavior has not yet been released. See #917

resource/gitlab_project: Mark `topics` attribute as `Computed`

---

docs/resources/project_access_token.md
examples/resources/gitlab_project_access_token/resource.tf
internal/provider/resource_gitlab_project_access_token.go
internal/provider/resource_gitlab_project_access_token_test.go

Add `access_level` to `gitlab_project_access_token` resource #994 

Add access_level to gitlab_project_access_token resource

---

internal/provider/resource_gitlab_project_access_token.go
internal/provider/resource_gitlab_project_access_token_test.go

Fixes #1002 
- Fixed a test bug where a hardcoded expiration date that passed caused failures
- Improved the destroy function to wait for the token to finish deleting
Note the diff to the `resourceGitlabProjectAccessTokenRead` looks large, but actually it is a straight move. I moved the list API calls into a `resourceGitlabProjectAccessTokenFind` function because I had to use it in the destroy logic also.
- …

gitlab_project_access_token: Test bugfix and destroy improvement

---

docs/resources/project_protected_environment.md
examples/resources/gitlab_project_protected_environment/resource.tf
internal/provider/resource_gitlab_project_protected_environment.go
internal/provider/resource_gitlab_project_protected_environment_test.go

Closes #1000 
The functional change is simply the removal of the `MaxItems: 1` field from the schema.
I decided to rewrite the tests because of how they were organized by access level type. To reduce duplication with my new test case, it made the most sense to combine them into a single test.
- Import …

resource/gitlab_project_protected_environment: Allow multiple deploy_access_levels

---

GNUmakefile

Fixes this error since upgrading to tfproviderdocs 0.7.0, which changed how the terraform binary is loaded. (I have an M1 mac, which I assume is the cause. It's always the cause. 😓 I tried upgrading to the latest Terraform for my local version, and that didn't help.)
```
make generate                                                                                                protected-environment-multi
GITLAB_TOKEN="" /Users/adam/repos/terraform-provider-gitlab/bin/tfplugindocs generate
rendering website for provider "terraform-provider-gitlab"
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "gitlab"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
Error executing …
```

Fix tfplugindocs generate error on M1 macs

---

docs/resources/group_access_token.md
internal/provider/resource_gitlab_group_access_token.go
internal/provider/resource_gitlab_group_access_token_test.go

The Gitlab API documentation does not mention the possibility to select access level 50 (=owner), but this option is both working (I verified it manually with an API call) and also exposed in the Gitlab UI:
- No new `//lintignore` comments were copied from existing code. (Linter …

add "owner" as valid access level for the group_access_token resource

---

internal/provider/resource_gitlab_service_slack.go

Resolves #1012
Slack service IDs where changed in https://github.com/gitlabhq/terraform-provider-gitlab/pull/821#discussion_r842671210 which breaks all existing `gitlab_service_slack` resources which were created before v3.9.0 of the Gitlab terraform provider.
- No new …

Fix `gitlab_service_slack` IDs

---

CHANGELOG.md

Update CHANGELOG to reflect #1013
Added warnings to past releases.
Removed a warning from 3.10.1, since that release did eventually get published.

Update changelog with #1013 bug fix

---

docs/resources/pipeline_trigger.md
internal/provider/resource_gitlab_pipeline_trigger.go

The `gitlab_pipeline_trigger` `token` attribute is actually a sensitive value. I think it's okay to mark it as sensitive in a minor release.

resource/gitlab_pipeline_trigger: Mark `token` attribute as sensitive

---

internal/provider/config.go
internal/provider/custom_attribute_helper.go
internal/provider/data_source_gitlab_group_membership.go
internal/provider/data_source_gitlab_project_issues.go
internal/provider/provider.go
internal/provider/provider_test.go
internal/provider/resource_gitlab_group_label.go
internal/provider/resource_gitlab_label.go
internal/provider/resource_gitlab_managed_license_test.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go
internal/provider/resource_gitlab_project_variable_test.go
internal/provider/resource_gitlab_repository_file.go
internal/provider/resource_gitlab_topic.go
internal/provider/resource_gitlab_user.go
internal/provider/util.go

This change set uses the context for all GitLab API calls.
Required:
* https://github.com/xanzy/go-gitlab/pull/1419

Use context for all GitLab API calls

---

docs/data-sources/repository_file.md
docs/resources/repository_file.md
go.mod
go.sum
internal/provider/data_source_gitlab_repository_file_test.go
internal/provider/resource_gitlab_repository_file.go
internal/provider/resource_gitlab_repository_file_test.go
internal/provider/schema_gitlab_repository_file.go

I've recently implemented the `execute_filemode` flag to the Repository
Files API. This change set makes it available in the provider, too :)
Blocked by:
- https://github.com/xanzy/go-gitlab/pull/1453
- GitLab 14.10 release and integration into the provider
Closes #981

resource/gitlab_repository_file: Add execute_filemode attribute

---

docs/resources/project.md
internal/provider/resource_gitlab_project.go

Added documentation to the `gitlab_project` resource describing a workaround to allow Terraform to manage the default branch protection on a project.

Add default branch protection workaround text to project resource

---

scripts/gitlab.rb

Enables GitLab Pages. Required for https://github.com/gitlabhq/terraform-provider-gitlab/pull/1026

Enable pages

---

.gitpod.yml
.vscode/settings.json
docs/resources/project.md
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

Adds a GitLab 15.0 check on the `build_coverage_regex` as it's set to be removed in GitLab 15.0. Based on conversations on our backwards compatibility issue, we still need to support the feature, however passing it will likely break the API in 15.0.
Partial Implements #1014
- No …

Deprecate branch coverage

---

docs/resources/project_mirror.md
go.sum
internal/provider/resource_gitlab_project_mirror.go
internal/provider/resource_gitlab_project_mirror_test.go

This change set add support for deletion on a destroy. It also switched to the new `GET` endpoint to retrieve a single project mirror instead of finding the proper one in the list `GET` endpoint.
It's currently blocked by:
* GitLab 14.10 release
* https://github.com/xanzy/go-gitlab/pull/1432 is merged

resource/gitlab_project_mirror: Support deletion on destroy

---

internal/provider/resource_gitlab_group.go

Update the allowable values for default_branch_protection according to the documentation 
https://docs.gitlab.com/ee/api/groups.html#options-for-default_branch_protection
- No new `//lintignore` comments were copied from existing code. (Linter rules are meant to be enforced on …

resource/gitlab_group: Update the allowable values for default_branch_protection

---

docs/resources/project_issue.md
internal/provider/schema_gitlab_project_issue.go

Some attributes were mistakenly marked as `Optional`, but they are
`Computed`-only.
See #1080

resource/gitlab_project_issue: Remove `Optional` from `Computed`-only attributes

---

go.mod
go.sum
internal/provider/resource_gitlab_group.go
internal/provider/resource_gitlab_group_test.go

fixes #574 
To test that the nested group is not recreated, I misused the AutoDevopsEnabled attribute. It ensures that the value is still true after transferring …

Moving a subgroup does not force a recreation of the group and no longer deletes the underlying projects

---

docs/resources/group_share_group.md
internal/provider/resource_gitlab_group_share_group.go

The documentation for the `group_id` and `group_share_id` currently 
suggests that this resource works the other way round than it actually does.
(none apply)

Clarify documentation on `gitlab_group_share_group` resource

---

docs/resources/service_jira.md
internal/provider/resource_gitlab_service_jira.go
internal/provider/resource_gitlab_service_jira_test.go

This change set cleans up a few things in the `gitlab_service_jira` resource:
* properly use resource ID in read function
* use passthrough importer
* state in docs that `jira_issue_transition_id` attribute cannot be imported
* add import verification test steps to `_basic` test and remove dedicated `_import` test

resource/gitlab_service_jira: several cleanup of tech debt

---

.github/workflows/pr-acceptance-ce.yml
.github/workflows/pr-acceptance-ee.yml
.github/workflows/push.yml
CONTRIBUTING.md
docker-compose.yml
docs/resources/managed_license.md
docs/resources/topic.md
examples/resources/gitlab_topic/resource.tf
internal/provider/data_source_gitlab_repository_file_test.go
internal/provider/helper_test.go
internal/provider/resource_gitlab_group_cluster_test.go
internal/provider/resource_gitlab_instance_cluster_test.go
internal/provider/resource_gitlab_managed_license.go
internal/provider/resource_gitlab_managed_license_test.go
internal/provider/resource_gitlab_project_cluster_test.go
internal/provider/resource_gitlab_project_test.go
internal/provider/resource_gitlab_repository_file_test.go
internal/provider/resource_gitlab_topic.go
internal/provider/resource_gitlab_topic_test.go

GitLab 15.0 has been released today 🎉 
This change set makes the provider compatible. We've missed a few things:
* The old K8s cluster integration was removed, therefore I've disabled the tests for GitLab 15.0 and onwards
* The `gitlab_managed_license` resource wasn't ready regarding the new `approval_status` values
@PatrickRice-KSC can you please verify the changes I did in the managed license resource? Did I miss something?
@PatrickRice-KSC @armsnyder @nagyv I've also changed the workflows to test the last three GitLab releases. WDYT? 🏓

Support Gitlab 15.0

---

internal/provider/resource_gitlab_service_microsoft_teams.go

This resulted in a nil pointer panic, because when a project wasn't found `p` would obv. be `nil`. 
Closes: #1110

Fix handling removal from state of microsoft teams integration resource

---

docs/resources/project.md
internal/provider/resource_gitlab_project.go

GitLab 14.10 released with a bugfix for the `default_branch` field in
the Projects REST API so that our custom logic is no longer required.
see https://gitlab.com/gitlab-org/gitlab/-/issues/333426
Once GitLab 15.1 is out I suggest to remove that code entirely.

resource/gitlab_project: Only execute custom `default_branch` logic for GitLab < 14.10

---

docs/resources/project_protected_environment.md
examples/resources/gitlab_project_protected_environment/resource.tf
internal/provider/resource_gitlab_project_protected_environment.go
internal/provider/resource_gitlab_project_protected_environment_test.go

Issue Add protected environments required_approval_count
https://github.com/gitlabhq/terraform-provider-gitlab/issues/1096
This is the PR for the dependency package:
https://github.com/xanzy/go-gitlab/pull/1482
- No new `//lintignore` comments were copied from existing code. …

Setup for required_approval_count in gitlab_project_protected_environment

---

docs/resources/project_approval_rule.md
examples/resources/gitlab_project_approval_rule/resource.tf

Pretty sure this is what was meant in the example.

fix resource type in docs for project_approval_rule.md

---

internal/provider/resource_gitlab_group.go
internal/provider/resource_gitlab_group_test.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

I think at one point we have to decide on a consistent strategy about how and when to set optional attributes for the API options ... I have a few ideas and I'll write them up in an issue.
Closes: #1151

resource/gitlab_project: Fix passing `false` to API for explicitly set optional attributes

---

internal/provider/resource_gitlab_group_ldap_link_test.go
internal/provider/resource_gitlab_group_membership.go
internal/provider/resource_gitlab_group_membership_test.go
internal/provider/resource_gitlab_group_share_group.go
internal/provider/resource_gitlab_project_membership_test.go

This PR is linked to [#1122](https://github.com/gitlabhq/terraform-provider-gitlab/pull/1122), as we wanted to keep PRs small.
This is a small clean-up for suggestions @timofurrer made in #1122 
- No new `//lintignore` comments were copied from existing code. (Linter rules are …

Clean up: date comment & fmt.Sprintf

---

docs/resources/project.md
internal/provider/resource_gitlab_project.go

Note the danger of using `approvals_before_merge` attribute in the project resource

---

internal/provider/resource_gitlab_user_sshkey.go
internal/provider/resource_gitlab_user_sshkey_test.go

This change set handles ssh keys with leading or trailing whitespaces gracefully - they are simply ignored when diffing and there won't trigger an update.
This is a probably a common source of issue when using it together with `tls_private_key.public_key_openssh` which appends a newline.
Closes: #1174

resource/gitlab_user_sshkey: Ignore leading and trailing whitespaces in key

---

CONTRIBUTING.md
GNUmakefile

This only works for macOS adm64 out of the box,
you may use `TERRAFORM_PLATFORM_DIR` and `TERRAFORM_PLUGIN_DIR`
to control the installation path.
You can use the provider using the following config:
```hcl
gitlab = {
version = "99.99.99"
source  = "gitlab.local/x/gitlab"
}
```

Add convenience cmd to build and install bin locally

---

internal/provider/resource_gitlab_group_access_token.go
internal/provider/resource_gitlab_project_access_token.go

We should be able to merge this :)

Use single `GET` endpoints to retrieve GAT and PAT

---

internal/provider/config.go

golangci-lint 1.42 on go 1.19 reports:
```
internal/provider/config.go:7:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
^
```
Not sure why it does not appear on GitHub CI.
- New …

Fix golangci by moving away from deprecated io/ioutil

---

docs/resources/cluster_agent_token.md
examples/resources/gitlab_cluster_agent_token/resource.tf

Fix typo in gitlab_cluster_agent_token example

---

.github/workflows/release.yml

HashiCorp's `ghaction-import-gpg` is deprecated, see
https://github.com/hashicorp/ghaction-import-gpg/issues/11#issuecomment-1185107410.

Use `crazy-max/ghaction-import-gpg` instead of the one from hashicorp

---

internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

Gitlab API only allows updating `ci_forward_deployment_enabled` when editing a project. Setting `ci_forward_deployment_enabled=false` at project creation has no effect. We need to `terraform apply` twice the apply the change.
Related Gitlab issues:
- https://gitlab.com/gitlab-org/gitlab/-/issues/341672
- https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44510
This MR add `ci_forward_deployment_enabled` to `editProjectOptions` to update the parameter after the creation.
- A …

resource/gitlab_project: Fix passing `ci_forward_deployment_enabled=false` at project creation

---

docs/resources/group_ldap_link.md
internal/provider/resource_gitlab_group_ldap_link.go

Add a note about the `ldap_provider` not being the LDAP `label` value
and add information on how to receive the LDAP server name using a rake
task.
Fixes https://github.com/gitlabhq/terraform-provider-gitlab/issues/605
- No new `//lintignore` comments were copied from existing …

resource_gitlab_group_ldap_link: Update docs

---

docs/resources/branch_protection.md
internal/provider/resource_gitlab_branch_protection.go
internal/provider/resource_gitlab_branch_protection_test.go

This change to the `gitlab_branch_protection` resource will allow to
protect the default branch of a project without importing. It basically
works by unprotecting and protecting the default branch again in case it
already exists when the resource is created. This allows the following
code to properly work:
```hcl
resource "gitlab_project" "example" {
name = "example"
initialize_with_readme = true
}
resource "gitlab_branch_protection" "default_branch" {
project = gitlab_project.example.id
branch = gitlab_project.example.default_branch
// ... whatever settings ...
}
```
The drawback of this is that it quickly unprotects the default branch to
protect it again in the above scenario. However, it already does that
for pretty much any update to the resource attributes, because of the
lack of a …

resource/gitlab_branch_protection: Allow to manage branch protection for default branch

---

docs/resources/group_membership.md
internal/provider/helper_test.go
internal/provider/resource_gitlab_group_membership.go
internal/provider/resource_gitlab_group_membership_test.go

This change will support the two options when removing a user from a
group using `gitlab_group_membership`. These are
`skip_subresources_on_destroy` and `unassign_issuables_on_destroy`.
Both default to `false` and the change is backwards compatible.
Closes: #1194
/cc @1oglop1

resource/gitlab_group_membership: Support removal options

---

internal/provider/resource_gitlab_group_label.go

Fix typo in the error message of the import command for `gitlab_group_label`. The doc states [here](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group_label#import) that it should be `terraform import gitlab_group_label.example <group ID>:<label name>` but the error message says `terraform import gitlab_group_label.example <group ID>.<label name>`
- New resources have at …

resource: fix typo in error message

---

scripts/gitlab.rb

This change configures a dummy SAML provider so that we can properly test the saml group link resource contributed with #1215 .

Enable dummy SAML provider to allow saml group link features

---

docs/data-sources/project.md
internal/provider/data_source_gitlab_project.go

I noticed that `data.gitlab_project` does not expose `ci_config_path`, this PR expose that field.

Add ci_config_path to data.gitlab_project

---

docs/data-sources/project.md
docs/data-sources/projects.md
docs/resources/project.md
internal/provider/data_source_gitlab_project.go
internal/provider/data_source_gitlab_projects.go
internal/provider/resource_gitlab_project.go
internal/provider/resource_gitlab_project_test.go

**Edit:** I just noticed that I mixed up the field names in my initial commit message. This is fixed now. 😓🙈 
Closes #1248.
- ~~[Examples](https://github.com/gitlabhq/terraform-provider-gitlab/tree/main/examples) are updated with:~~
- ~~A \*.tf file for the resource/s with at least one usage example~~
- ~~A \*.sh file for the resource/s with an import example (if applicable)~~
- ~~New resources have at minimum a basic test with three steps:~~
- ~~Create the resource~~
- ~~Update the attributes~~
- ~~Import the resource~~

gitlab_projects(s): Add suggestion_commit_message

---

docs/resources/branch_protection.md
internal/provider/access_level_helpers.go

This value was simply missing, the truth of allowed ones is here: https://gitlab.com/gitlab-org/gitlab/blob/d2b99cadd0204030bf789ea1523b4e02c9f2535b/app/models/concerns/protected_ref_access.rb#L12
Closes: #1267

resource/gitlab_branch_protection: Support `no one` in `unprotect_access_level`

---

.github/workflows/lock.yml

Lock down PRs for repository migration over to GitLab
